[project]
name = "fireflyiii-enricher-core"
version = "0.7.0"
description = "A core library for enriching Firefly III transactions"
authors = [{ name = "wini83", email = "rico.gotti210@gmail.com" }]
readme = "README.md"
license = { text = "MIT" }
requires-python = ">=3.12"

classifiers = [
    "Programming Language :: Python :: Python :: 3",
    "Operating System :: OS Independent",
]

# --------------------
# Runtime dependencies
# --------------------
dependencies = [
    "httpx",
]

# --------------------
# Optional dependencies
# --------------------
# [project.optional-dependencies]
# dev = [
#     "pytest",
#     "ruff",
#     "mypy",
#     "types-requests",  # może wylecieć później, jak migracja do httpx będzie complete
#     "commitizen",
#     "python-dotenv",   # tylko testy / example_minimal
# ]

# --------------------
# Commitizen
# --------------------
[tool.commitizen]
name = "cz_conventional_commits"
version = "0.7.0"
tag_format = "v$version"
version_files = ["pyproject.toml"]
update_changelog_on_bump = true
annotated_tags = true

# --------------------
# Ruff (lint + format + isort replacement)
# --------------------
[tool.ruff]
line-length = 88
target-version = "py312"

exclude = [
    ".git",
    ".venv",
    "__pycache__",
    "build",
    "dist",
]

[tool.ruff.lint]
select = [
    "E",
    "F",
    "I",
    "N",
]

ignore = [
    "N818",
]

[tool.ruff.format]
quote-style = "double"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"

# --------------------
# MyPy
# --------------------
[tool.mypy]
python_version = "3.12"
strict = true
ignore_missing_imports = true
exclude = ["build"]

# --------------------
# Build backend
# --------------------
[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "pydantic-settings>=2.12.0",
    "pytest",
    "ruff",
    "mypy",
    "commitizen",
    "python-dotenv",   # tylko testy / example_minimal
]

[tool.setuptools.package-data]
"fireflyiii_enricher_core" = ["py.typed"]
