# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional, Union
from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from openapi_client.models.account_role_property import AccountRoleProperty
from openapi_client.models.credit_card_type_property import CreditCardTypeProperty
from openapi_client.models.interest_period_property import InterestPeriodProperty
from openapi_client.models.liability_direction_property import (
    LiabilityDirectionProperty,
)
from openapi_client.models.liability_type_property import LiabilityTypeProperty
from openapi_client.models.short_account_type_property import ShortAccountTypeProperty


class AccountStore(BaseModel):
    """
    AccountStore
    """

    name: StrictStr = Field(...)
    type: ShortAccountTypeProperty = Field(...)
    iban: Optional[StrictStr] = None
    bic: Optional[StrictStr] = None
    account_number: Optional[StrictStr] = None
    opening_balance: Optional[StrictStr] = Field(
        default=None,
        description="Represents the opening balance, the initial amount this account holds.",
    )
    opening_balance_date: Optional[datetime] = Field(
        default=None, description="Represents the date of the opening balance."
    )
    virtual_balance: Optional[StrictStr] = None
    currency_id: Optional[StrictStr] = Field(
        default=None,
        description="Use either currency_id or currency_code. Defaults to the user's financial administration's currency.",
    )
    currency_code: Optional[StrictStr] = Field(
        default=None,
        description="Use either currency_id or currency_code. Defaults to the user's financial administration's currency.",
    )
    active: Optional[StrictBool] = Field(
        default=True, description="If omitted, defaults to true."
    )
    order: Optional[StrictInt] = Field(default=None, description="Order of the account")
    include_net_worth: Optional[StrictBool] = Field(
        default=True, description="If omitted, defaults to true."
    )
    account_role: Optional[AccountRoleProperty] = None
    credit_card_type: Optional[CreditCardTypeProperty] = None
    monthly_payment_date: Optional[datetime] = Field(
        default=None,
        description="Mandatory when the account_role is ccAsset. Moment at which CC payment installments are asked for by the bank.",
    )
    liability_type: Optional[LiabilityTypeProperty] = None
    liability_direction: Optional[LiabilityDirectionProperty] = None
    interest: Optional[StrictStr] = Field(
        default="0",
        description="Mandatory when type is liability. Interest percentage.",
    )
    interest_period: Optional[InterestPeriodProperty] = None
    notes: Optional[StrictStr] = None
    latitude: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Latitude of the accounts's location, if applicable. Can be used to draw a map.",
    )
    longitude: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Latitude of the accounts's location, if applicable. Can be used to draw a map.",
    )
    zoom_level: Optional[StrictInt] = Field(
        default=None,
        description="Zoom level for the map, if drawn. This to set the box right. Unfortunately this is a proprietary value because each map provider has different zoom levels.",
    )
    __properties = [
        "name",
        "type",
        "iban",
        "bic",
        "account_number",
        "opening_balance",
        "opening_balance_date",
        "virtual_balance",
        "currency_id",
        "currency_code",
        "active",
        "order",
        "include_net_worth",
        "account_role",
        "credit_card_type",
        "monthly_payment_date",
        "liability_type",
        "liability_direction",
        "interest",
        "interest_period",
        "notes",
        "latitude",
        "longitude",
        "zoom_level",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AccountStore:
        """Create an instance of AccountStore from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # set to None if iban (nullable) is None
        # and __fields_set__ contains the field
        if self.iban is None and "iban" in self.__fields_set__:
            _dict["iban"] = None

        # set to None if bic (nullable) is None
        # and __fields_set__ contains the field
        if self.bic is None and "bic" in self.__fields_set__:
            _dict["bic"] = None

        # set to None if account_number (nullable) is None
        # and __fields_set__ contains the field
        if self.account_number is None and "account_number" in self.__fields_set__:
            _dict["account_number"] = None

        # set to None if opening_balance_date (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.opening_balance_date is None
            and "opening_balance_date" in self.__fields_set__
        ):
            _dict["opening_balance_date"] = None

        # set to None if account_role (nullable) is None
        # and __fields_set__ contains the field
        if self.account_role is None and "account_role" in self.__fields_set__:
            _dict["account_role"] = None

        # set to None if credit_card_type (nullable) is None
        # and __fields_set__ contains the field
        if self.credit_card_type is None and "credit_card_type" in self.__fields_set__:
            _dict["credit_card_type"] = None

        # set to None if monthly_payment_date (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.monthly_payment_date is None
            and "monthly_payment_date" in self.__fields_set__
        ):
            _dict["monthly_payment_date"] = None

        # set to None if liability_type (nullable) is None
        # and __fields_set__ contains the field
        if self.liability_type is None and "liability_type" in self.__fields_set__:
            _dict["liability_type"] = None

        # set to None if liability_direction (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.liability_direction is None
            and "liability_direction" in self.__fields_set__
        ):
            _dict["liability_direction"] = None

        # set to None if interest (nullable) is None
        # and __fields_set__ contains the field
        if self.interest is None and "interest" in self.__fields_set__:
            _dict["interest"] = None

        # set to None if interest_period (nullable) is None
        # and __fields_set__ contains the field
        if self.interest_period is None and "interest_period" in self.__fields_set__:
            _dict["interest_period"] = None

        # set to None if notes (nullable) is None
        # and __fields_set__ contains the field
        if self.notes is None and "notes" in self.__fields_set__:
            _dict["notes"] = None

        # set to None if latitude (nullable) is None
        # and __fields_set__ contains the field
        if self.latitude is None and "latitude" in self.__fields_set__:
            _dict["latitude"] = None

        # set to None if longitude (nullable) is None
        # and __fields_set__ contains the field
        if self.longitude is None and "longitude" in self.__fields_set__:
            _dict["longitude"] = None

        # set to None if zoom_level (nullable) is None
        # and __fields_set__ contains the field
        if self.zoom_level is None and "zoom_level" in self.__fields_set__:
            _dict["zoom_level"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AccountStore:
        """Create an instance of AccountStore from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AccountStore.parse_obj(obj)

        _obj = AccountStore.parse_obj(
            {
                "name": obj.get("name"),
                "type": obj.get("type"),
                "iban": obj.get("iban"),
                "bic": obj.get("bic"),
                "account_number": obj.get("account_number"),
                "opening_balance": obj.get("opening_balance"),
                "opening_balance_date": obj.get("opening_balance_date"),
                "virtual_balance": obj.get("virtual_balance"),
                "currency_id": obj.get("currency_id"),
                "currency_code": obj.get("currency_code"),
                "active": obj.get("active") if obj.get("active") is not None else True,
                "order": obj.get("order"),
                "include_net_worth": (
                    obj.get("include_net_worth")
                    if obj.get("include_net_worth") is not None
                    else True
                ),
                "account_role": obj.get("account_role"),
                "credit_card_type": obj.get("credit_card_type"),
                "monthly_payment_date": obj.get("monthly_payment_date"),
                "liability_type": obj.get("liability_type"),
                "liability_direction": obj.get("liability_direction"),
                "interest": (
                    obj.get("interest") if obj.get("interest") is not None else "0"
                ),
                "interest_period": obj.get("interest_period"),
                "notes": obj.get("notes"),
                "latitude": obj.get("latitude"),
                "longitude": obj.get("longitude"),
                "zoom_level": obj.get("zoom_level"),
            }
        )
        return _obj
