# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional, Union
from pydantic import BaseModel, Field, StrictBool, StrictFloat, StrictInt, StrictStr
from openapi_client.models.account_role_property import AccountRoleProperty
from openapi_client.models.credit_card_type_property import CreditCardTypeProperty
from openapi_client.models.interest_period_property import InterestPeriodProperty
from openapi_client.models.liability_direction_property import (
    LiabilityDirectionProperty,
)
from openapi_client.models.liability_type_property import LiabilityTypeProperty
from openapi_client.models.short_account_type_property import ShortAccountTypeProperty


class AccountProperties(BaseModel):
    """
    AccountProperties
    """

    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    active: Optional[StrictBool] = True
    order: Optional[StrictInt] = Field(
        default=None,
        description="Order of the account. Is NULL if account is not asset or liability.",
    )
    name: StrictStr = Field(...)
    type: ShortAccountTypeProperty = Field(...)
    account_role: Optional[AccountRoleProperty] = None
    object_group_id: Optional[StrictStr] = Field(
        default=None,
        description="The group ID of the group this object is part of. NULL if no group.",
    )
    object_group_order: Optional[StrictInt] = Field(
        default=None,
        description="The order of the group. At least 1, for the highest sorting.",
    )
    object_group_title: Optional[StrictStr] = Field(
        default=None, description="The name of the group. NULL if no group."
    )
    object_has_currency_setting: Optional[StrictBool] = Field(
        default=None,
        description="Indicates whether the account has a currency setting. If false, the account uses the administration's primary currency. Asset accounts and liability accounts always have a currency setting, while expense and revenue accounts do not.",
    )
    currency_id: Optional[StrictStr] = Field(
        default=None,
        description="The currency ID of the currency associated with this object.",
    )
    currency_name: Optional[StrictStr] = Field(
        default=None,
        description="The currency name of the currency associated with this object.",
    )
    currency_code: Optional[StrictStr] = Field(
        default=None,
        description="The currency code of the currency associated with this object.",
    )
    currency_symbol: Optional[StrictStr] = None
    currency_decimal_places: Optional[StrictInt] = None
    primary_currency_id: Optional[StrictStr] = Field(
        default=None,
        description="The currency ID of the administration's primary currency.",
    )
    primary_currency_name: Optional[StrictStr] = Field(
        default=None,
        description="The currency name of the administration's primary currency.",
    )
    primary_currency_code: Optional[StrictStr] = Field(
        default=None,
        description="The currency code of the administration's primary currency.",
    )
    primary_currency_symbol: Optional[StrictStr] = Field(
        default=None,
        description="The currency symbol of the administration's primary currency.",
    )
    primary_currency_decimal_places: Optional[StrictInt] = Field(
        default=None,
        description="The currency decimal places of the administration's primary currency.",
    )
    current_balance: Optional[StrictStr] = Field(
        default=None,
        description="The current balance of the account in the account's currency. If the account has no currency, this is the balance in the administration's primary currency. Either way, the `currency_*` fields reflect the currency used.",
    )
    pc_current_balance: Optional[StrictStr] = Field(
        default=None,
        description="The current balance of the account in the administration's primary currency. The `primary_currency_*` fields reflect the currency used. This field is NULL if the user does have 'convert to primary' set to true in their settings.",
    )
    balance_difference: Optional[StrictStr] = Field(
        default=None,
        description="If you submit a start AND end date, this will be the difference between those two moments.",
    )
    pc_balance_difference: Optional[StrictStr] = Field(
        default=None,
        description="If you submit a start AND end date, this will be the difference in the currency of the account or the administration's primary currency between those two moments.",
    )
    opening_balance: Optional[StrictStr] = Field(
        default=None,
        description="Represents the opening balance, the initial amount this account holds in the currency of the account or the administration's primary currency if the account has no currency. Either way, the `currency_*` fields reflect the currency used.",
    )
    pc_opening_balance: Optional[StrictStr] = Field(
        default=None,
        description="The opening balance of the account in the administration's primary currency (pc). The `primary_currency_*` fields reflect the currency used. This field is NULL if the user does have 'convert to primary' set to true in their settings.",
    )
    virtual_balance: Optional[StrictStr] = Field(
        default=None,
        description="The virtual balance of the account in the account's currency or the administration's primary currency if the account has no currency.",
    )
    pc_virtual_balance: Optional[StrictStr] = Field(
        default=None,
        description="The virtual balance of the account in the administration's primary currency (pc). The `primary_currency_*` fields reflect the currency used. This field is NULL if the user does have 'convert to primary' set to true in their settings.",
    )
    debt_amount: Optional[StrictStr] = Field(
        default=None,
        description="In liability accounts (loans, debts and mortgages), this is the amount of debt in the account's currency (see the `currency_*` fields). In asset accounts, this is NULL.",
    )
    pc_debt_amount: Optional[StrictStr] = Field(
        default=None,
        description="In liability accounts (loans, debts and mortgages), this is the amount of debt in the administration's primary currency (see the `currency_*` fields. In asset accounts, this is NULL.",
    )
    current_balance_date: Optional[datetime] = Field(
        default=None,
        description="The timestamp for this date is always 23:59:59, to indicate it's the balance at the very END of that particular day.",
    )
    notes: Optional[StrictStr] = None
    monthly_payment_date: Optional[datetime] = Field(
        default=None,
        description="Mandatory when the account_role is ccAsset. Moment at which CC payment installments are asked for by the bank.",
    )
    credit_card_type: Optional[CreditCardTypeProperty] = None
    account_number: Optional[StrictStr] = None
    iban: Optional[StrictStr] = None
    bic: Optional[StrictStr] = None
    opening_balance_date: Optional[datetime] = Field(
        default=None, description="Represents the date of the opening balance."
    )
    liability_type: Optional[LiabilityTypeProperty] = None
    liability_direction: Optional[LiabilityDirectionProperty] = None
    interest: Optional[StrictStr] = Field(
        default=None,
        description="Mandatory when type is liability. Interest percentage.",
    )
    interest_period: Optional[InterestPeriodProperty] = None
    include_net_worth: Optional[StrictBool] = True
    longitude: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Latitude of the accounts's location, if applicable. Can be used to draw a map.",
    )
    latitude: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Latitude of the accounts's location, if applicable. Can be used to draw a map.",
    )
    zoom_level: Optional[StrictInt] = Field(
        default=None,
        description="Zoom level for the map, if drawn. This to set the box right. Unfortunately this is a proprietary value because each map provider has different zoom levels.",
    )
    last_activity: Optional[datetime] = Field(
        default=None, description="Last activity of the account."
    )
    __properties = [
        "created_at",
        "updated_at",
        "active",
        "order",
        "name",
        "type",
        "account_role",
        "object_group_id",
        "object_group_order",
        "object_group_title",
        "object_has_currency_setting",
        "currency_id",
        "currency_name",
        "currency_code",
        "currency_symbol",
        "currency_decimal_places",
        "primary_currency_id",
        "primary_currency_name",
        "primary_currency_code",
        "primary_currency_symbol",
        "primary_currency_decimal_places",
        "current_balance",
        "pc_current_balance",
        "balance_difference",
        "pc_balance_difference",
        "opening_balance",
        "pc_opening_balance",
        "virtual_balance",
        "pc_virtual_balance",
        "debt_amount",
        "pc_debt_amount",
        "current_balance_date",
        "notes",
        "monthly_payment_date",
        "credit_card_type",
        "account_number",
        "iban",
        "bic",
        "opening_balance_date",
        "liability_type",
        "liability_direction",
        "interest",
        "interest_period",
        "include_net_worth",
        "longitude",
        "latitude",
        "zoom_level",
        "last_activity",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AccountProperties:
        """Create an instance of AccountProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(
            by_alias=True,
            exclude={
                "created_at",
                "updated_at",
                "object_group_order",
                "object_has_currency_setting",
                "currency_symbol",
                "currency_decimal_places",
                "primary_currency_id",
                "primary_currency_name",
                "primary_currency_code",
                "primary_currency_symbol",
                "primary_currency_decimal_places",
                "current_balance",
                "pc_current_balance",
                "balance_difference",
                "pc_balance_difference",
                "current_balance_date",
            },
            exclude_none=True,
        )
        # set to None if order (nullable) is None
        # and __fields_set__ contains the field
        if self.order is None and "order" in self.__fields_set__:
            _dict["order"] = None

        # set to None if account_role (nullable) is None
        # and __fields_set__ contains the field
        if self.account_role is None and "account_role" in self.__fields_set__:
            _dict["account_role"] = None

        # set to None if object_group_id (nullable) is None
        # and __fields_set__ contains the field
        if self.object_group_id is None and "object_group_id" in self.__fields_set__:
            _dict["object_group_id"] = None

        # set to None if object_group_order (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.object_group_order is None
            and "object_group_order" in self.__fields_set__
        ):
            _dict["object_group_order"] = None

        # set to None if object_group_title (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.object_group_title is None
            and "object_group_title" in self.__fields_set__
        ):
            _dict["object_group_title"] = None

        # set to None if pc_current_balance (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.pc_current_balance is None
            and "pc_current_balance" in self.__fields_set__
        ):
            _dict["pc_current_balance"] = None

        # set to None if pc_balance_difference (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.pc_balance_difference is None
            and "pc_balance_difference" in self.__fields_set__
        ):
            _dict["pc_balance_difference"] = None

        # set to None if debt_amount (nullable) is None
        # and __fields_set__ contains the field
        if self.debt_amount is None and "debt_amount" in self.__fields_set__:
            _dict["debt_amount"] = None

        # set to None if pc_debt_amount (nullable) is None
        # and __fields_set__ contains the field
        if self.pc_debt_amount is None and "pc_debt_amount" in self.__fields_set__:
            _dict["pc_debt_amount"] = None

        # set to None if notes (nullable) is None
        # and __fields_set__ contains the field
        if self.notes is None and "notes" in self.__fields_set__:
            _dict["notes"] = None

        # set to None if monthly_payment_date (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.monthly_payment_date is None
            and "monthly_payment_date" in self.__fields_set__
        ):
            _dict["monthly_payment_date"] = None

        # set to None if credit_card_type (nullable) is None
        # and __fields_set__ contains the field
        if self.credit_card_type is None and "credit_card_type" in self.__fields_set__:
            _dict["credit_card_type"] = None

        # set to None if account_number (nullable) is None
        # and __fields_set__ contains the field
        if self.account_number is None and "account_number" in self.__fields_set__:
            _dict["account_number"] = None

        # set to None if iban (nullable) is None
        # and __fields_set__ contains the field
        if self.iban is None and "iban" in self.__fields_set__:
            _dict["iban"] = None

        # set to None if bic (nullable) is None
        # and __fields_set__ contains the field
        if self.bic is None and "bic" in self.__fields_set__:
            _dict["bic"] = None

        # set to None if opening_balance_date (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.opening_balance_date is None
            and "opening_balance_date" in self.__fields_set__
        ):
            _dict["opening_balance_date"] = None

        # set to None if liability_type (nullable) is None
        # and __fields_set__ contains the field
        if self.liability_type is None and "liability_type" in self.__fields_set__:
            _dict["liability_type"] = None

        # set to None if liability_direction (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.liability_direction is None
            and "liability_direction" in self.__fields_set__
        ):
            _dict["liability_direction"] = None

        # set to None if interest (nullable) is None
        # and __fields_set__ contains the field
        if self.interest is None and "interest" in self.__fields_set__:
            _dict["interest"] = None

        # set to None if interest_period (nullable) is None
        # and __fields_set__ contains the field
        if self.interest_period is None and "interest_period" in self.__fields_set__:
            _dict["interest_period"] = None

        # set to None if longitude (nullable) is None
        # and __fields_set__ contains the field
        if self.longitude is None and "longitude" in self.__fields_set__:
            _dict["longitude"] = None

        # set to None if latitude (nullable) is None
        # and __fields_set__ contains the field
        if self.latitude is None and "latitude" in self.__fields_set__:
            _dict["latitude"] = None

        # set to None if zoom_level (nullable) is None
        # and __fields_set__ contains the field
        if self.zoom_level is None and "zoom_level" in self.__fields_set__:
            _dict["zoom_level"] = None

        # set to None if last_activity (nullable) is None
        # and __fields_set__ contains the field
        if self.last_activity is None and "last_activity" in self.__fields_set__:
            _dict["last_activity"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AccountProperties:
        """Create an instance of AccountProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AccountProperties.parse_obj(obj)

        _obj = AccountProperties.parse_obj(
            {
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
                "active": obj.get("active") if obj.get("active") is not None else True,
                "order": obj.get("order"),
                "name": obj.get("name"),
                "type": obj.get("type"),
                "account_role": obj.get("account_role"),
                "object_group_id": obj.get("object_group_id"),
                "object_group_order": obj.get("object_group_order"),
                "object_group_title": obj.get("object_group_title"),
                "object_has_currency_setting": obj.get("object_has_currency_setting"),
                "currency_id": obj.get("currency_id"),
                "currency_name": obj.get("currency_name"),
                "currency_code": obj.get("currency_code"),
                "currency_symbol": obj.get("currency_symbol"),
                "currency_decimal_places": obj.get("currency_decimal_places"),
                "primary_currency_id": obj.get("primary_currency_id"),
                "primary_currency_name": obj.get("primary_currency_name"),
                "primary_currency_code": obj.get("primary_currency_code"),
                "primary_currency_symbol": obj.get("primary_currency_symbol"),
                "primary_currency_decimal_places": obj.get(
                    "primary_currency_decimal_places"
                ),
                "current_balance": obj.get("current_balance"),
                "pc_current_balance": obj.get("pc_current_balance"),
                "balance_difference": obj.get("balance_difference"),
                "pc_balance_difference": obj.get("pc_balance_difference"),
                "opening_balance": obj.get("opening_balance"),
                "pc_opening_balance": obj.get("pc_opening_balance"),
                "virtual_balance": obj.get("virtual_balance"),
                "pc_virtual_balance": obj.get("pc_virtual_balance"),
                "debt_amount": obj.get("debt_amount"),
                "pc_debt_amount": obj.get("pc_debt_amount"),
                "current_balance_date": obj.get("current_balance_date"),
                "notes": obj.get("notes"),
                "monthly_payment_date": obj.get("monthly_payment_date"),
                "credit_card_type": obj.get("credit_card_type"),
                "account_number": obj.get("account_number"),
                "iban": obj.get("iban"),
                "bic": obj.get("bic"),
                "opening_balance_date": obj.get("opening_balance_date"),
                "liability_type": obj.get("liability_type"),
                "liability_direction": obj.get("liability_direction"),
                "interest": obj.get("interest"),
                "interest_period": obj.get("interest_period"),
                "include_net_worth": (
                    obj.get("include_net_worth")
                    if obj.get("include_net_worth") is not None
                    else True
                ),
                "longitude": obj.get("longitude"),
                "latitude": obj.get("latitude"),
                "zoom_level": obj.get("zoom_level"),
                "last_activity": obj.get("last_activity"),
            }
        )
        return _obj
