# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg


class AccountTypeFilter(str, Enum):
    """
    AccountTypeFilter
    """

    """
    allowed enum values
    """
    ALL = "all"
    ASSET = "asset"
    CASH = "cash"
    EXPENSE = "expense"
    REVENUE = "revenue"
    SPECIAL = "special"
    HIDDEN = "hidden"
    LIABILITY = "liability"
    LIABILITIES = "liabilities"
    DEFAULT_ACCOUNT = "Default account"
    CASH_ACCOUNT = "Cash account"
    ASSET_ACCOUNT = "Asset account"
    EXPENSE_ACCOUNT = "Expense account"
    REVENUE_ACCOUNT = "Revenue account"
    INITIAL_BALANCE_ACCOUNT = "Initial balance account"
    BENEFICIARY_ACCOUNT = "Beneficiary account"
    IMPORT_ACCOUNT = "Import account"
    RECONCILIATION_ACCOUNT = "Reconciliation account"
    LOAN = "Loan"
    DEBT = "Debt"
    MORTGAGE = "Mortgage"

    @classmethod
    def from_json(cls, json_str: str) -> AccountTypeFilter:
        """Create an instance of AccountTypeFilter from a JSON string"""
        return AccountTypeFilter(json.loads(json_str))
