# coding: utf-8

"""
    Firefly III API v6.5.5

    This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2026-03-15 @ 08:08:22 (Europe/Amsterdam)</small> 

    The version of the OpenAPI document: v6.5.5
    Contact: james@firefly-iii.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AccountSearchFieldFilter(str, Enum):
    """
    AccountSearchFieldFilter
    """

    """
    allowed enum values
    """
    ALL = 'all'
    IBAN = 'iban'
    NAME = 'name'
    NUMBER = 'number'
    ID = 'id'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AccountSearchFieldFilter from a JSON string"""
        return cls(json.loads(json_str))


