# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr
from openapi_client.models.attachable_type import AttachableType


class AttachmentProperties(BaseModel):
    """
    AttachmentProperties
    """

    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    attachable_type: Optional[AttachableType] = None
    attachable_id: Optional[StrictStr] = Field(
        default=None, description="ID of the model this attachment is linked to."
    )
    hash: Optional[StrictStr] = Field(
        default=None, description="Hash of the file for basic duplicate detection."
    )
    filename: Optional[StrictStr] = None
    download_url: Optional[StrictStr] = None
    upload_url: Optional[StrictStr] = None
    title: Optional[StrictStr] = None
    notes: Optional[StrictStr] = None
    mime: Optional[StrictStr] = None
    size: Optional[StrictInt] = None
    __properties = [
        "created_at",
        "updated_at",
        "attachable_type",
        "attachable_id",
        "hash",
        "filename",
        "download_url",
        "upload_url",
        "title",
        "notes",
        "mime",
        "size",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AttachmentProperties:
        """Create an instance of AttachmentProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(
            by_alias=True,
            exclude={
                "created_at",
                "updated_at",
                "mime",
                "size",
            },
            exclude_none=True,
        )
        # set to None if title (nullable) is None
        # and __fields_set__ contains the field
        if self.title is None and "title" in self.__fields_set__:
            _dict["title"] = None

        # set to None if notes (nullable) is None
        # and __fields_set__ contains the field
        if self.notes is None and "notes" in self.__fields_set__:
            _dict["notes"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AttachmentProperties:
        """Create an instance of AttachmentProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AttachmentProperties.parse_obj(obj)

        _obj = AttachmentProperties.parse_obj(
            {
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
                "attachable_type": obj.get("attachable_type"),
                "attachable_id": obj.get("attachable_id"),
                "hash": obj.get("hash"),
                "filename": obj.get("filename"),
                "download_url": obj.get("download_url"),
                "upload_url": obj.get("upload_url"),
                "title": obj.get("title"),
                "notes": obj.get("notes"),
                "mime": obj.get("mime"),
                "size": obj.get("size"),
            }
        )
        return _obj
