# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr
from openapi_client.models.attachable_type import AttachableType


class AttachmentStore(BaseModel):
    """
    AttachmentStore
    """

    filename: StrictStr = Field(...)
    attachable_type: AttachableType = Field(...)
    attachable_id: StrictStr = Field(
        default=..., description="ID of the model this attachment is linked to."
    )
    title: Optional[StrictStr] = None
    notes: Optional[StrictStr] = None
    __properties = ["filename", "attachable_type", "attachable_id", "title", "notes"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AttachmentStore:
        """Create an instance of AttachmentStore from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # set to None if notes (nullable) is None
        # and __fields_set__ contains the field
        if self.notes is None and "notes" in self.__fields_set__:
            _dict["notes"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AttachmentStore:
        """Create an instance of AttachmentStore from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AttachmentStore.parse_obj(obj)

        _obj = AttachmentStore.parse_obj(
            {
                "filename": obj.get("filename"),
                "attachable_type": obj.get("attachable_type"),
                "attachable_id": obj.get("attachable_id"),
                "title": obj.get("title"),
                "notes": obj.get("notes"),
            }
        )
        return _obj
