# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr


class AutocompletePiggy(BaseModel):
    """
    AutocompletePiggy
    """

    id: StrictStr = Field(...)
    name: StrictStr = Field(
        default=...,
        description="Name of the piggy bank found by an auto-complete search.",
    )
    currency_id: Optional[StrictStr] = Field(
        default=None,
        description="Currency ID for this piggy bank. This will always be the currency of the piggy bank, never the user's primary currency.",
    )
    currency_code: Optional[StrictStr] = Field(
        default=None,
        description="Currency code for this piggy bank. This will always be the currency of the piggy bank, never the user's primary currency.",
    )
    currency_symbol: Optional[StrictStr] = None
    currency_name: Optional[StrictStr] = Field(
        default=None,
        description="Currency name for the currency used by this piggy bank. This will always be the currency of the piggy bank, never the user's primary currency.",
    )
    currency_decimal_places: Optional[StrictInt] = Field(
        default=None,
        description="Number of decimal places for the currency used by this piggy bank. This will always be the currency of the piggy bank, never the user's primary currency.",
    )
    object_group_id: Optional[StrictStr] = Field(
        default=None,
        description="The group ID of the group this object is part of. NULL if no group.",
    )
    object_group_title: Optional[StrictStr] = Field(
        default=None, description="The name of the group. NULL if no group."
    )
    __properties = [
        "id",
        "name",
        "currency_id",
        "currency_code",
        "currency_symbol",
        "currency_name",
        "currency_decimal_places",
        "object_group_id",
        "object_group_title",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AutocompletePiggy:
        """Create an instance of AutocompletePiggy from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # set to None if object_group_id (nullable) is None
        # and __fields_set__ contains the field
        if self.object_group_id is None and "object_group_id" in self.__fields_set__:
            _dict["object_group_id"] = None

        # set to None if object_group_title (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.object_group_title is None
            and "object_group_title" in self.__fields_set__
        ):
            _dict["object_group_title"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AutocompletePiggy:
        """Create an instance of AutocompletePiggy from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AutocompletePiggy.parse_obj(obj)

        _obj = AutocompletePiggy.parse_obj(
            {
                "id": obj.get("id"),
                "name": obj.get("name"),
                "currency_id": obj.get("currency_id"),
                "currency_code": obj.get("currency_code"),
                "currency_symbol": obj.get("currency_symbol"),
                "currency_name": obj.get("currency_name"),
                "currency_decimal_places": obj.get("currency_decimal_places"),
                "object_group_id": obj.get("object_group_id"),
                "object_group_title": obj.get("object_group_title"),
            }
        )
        return _obj
