# coding: utf-8

"""
    Firefly III API v6.7.4

    This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2026-09-27 @ 08:07:35 (Europe/Amsterdam)</small> 

    The version of the OpenAPI document: v6.7.4
    Contact: james@firefly-iii.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class AutoBudgetPeriod(str, Enum):
    """
    Period for the auto budget
    """

    """
    allowed enum values
    """
    DAILY = 'daily'
    WEEKLY = 'weekly'
    MONTHLY = 'monthly'
    QUARTERLY = 'quarterly'
    HALF_MINUS_YEAR = 'half-year'
    YEARLY = 'yearly'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of AutoBudgetPeriod from a JSON string"""
        return cls(json.loads(json_str))


