# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr


class AutocompleteAccount(BaseModel):
    """
    AutocompleteAccount
    """

    id: StrictStr = Field(...)
    name: StrictStr = Field(
        default=..., description="Name of the account found by an auto-complete search."
    )
    name_with_balance: StrictStr = Field(
        default=...,
        description="Asset accounts and liabilities have a second field with the given date's account balance in the account currency or primary currency.",
    )
    active: Optional[StrictBool] = Field(
        default=None, description="Is the bill active or not?"
    )
    type: StrictStr = Field(
        default=...,
        description="Account type of the account found by the auto-complete search.",
    )
    currency_id: StrictStr = Field(
        default=...,
        description="ID for the currency used by this account. If the user prefers amounts converted to their primary currency, this primary currency is used instead.",
    )
    currency_name: StrictStr = Field(
        default=...,
        description="Currency name for the currency used by this account. If the user prefers amounts converted to their primary currency, this primary currency is used instead.",
    )
    currency_code: StrictStr = Field(
        default=...,
        description="Currency code for the currency used by this account. If the user prefers amounts converted to their primary currency, this primary currency is used instead.",
    )
    currency_symbol: StrictStr = Field(
        default=...,
        description="Currency symbol for the currency used by this account. If the user prefers amounts converted to their primary currency, this primary currency is used instead.",
    )
    currency_decimal_places: StrictInt = Field(
        default=...,
        description="Number of decimal places for the currency used by this account. If the user prefers amounts converted to their primary currency, this primary currency is used instead.",
    )
    account_currency_id: Optional[StrictStr] = Field(
        default=None,
        description='ID for the currency used by this account. Even if "convertToPrimary" is on, the account currency ID is displayed here.',
    )
    account_currency_name: Optional[StrictStr] = Field(
        default=None,
        description='Name for the currency used by this account. Even if "convertToPrimary" is on, the account currency name is displayed here.',
    )
    account_currency_code: Optional[StrictStr] = Field(
        default=None,
        description='Code for the currency used by this account. Even if "convertToPrimary" is on, the account currency code is displayed here.',
    )
    account_currency_symbol: Optional[StrictStr] = Field(
        default=None,
        description='Code for the currency used by this account. Even if "convertToPrimary" is on, the account currency code is displayed here.',
    )
    account_currency_decimal_places: Optional[StrictInt] = Field(
        default=None,
        description='Number of decimal places for the currency used by this account. Even if "convertToPrimary" is on, the account currency code is displayed here.',
    )
    __properties = [
        "id",
        "name",
        "name_with_balance",
        "active",
        "type",
        "currency_id",
        "currency_name",
        "currency_code",
        "currency_symbol",
        "currency_decimal_places",
        "account_currency_id",
        "account_currency_name",
        "account_currency_code",
        "account_currency_symbol",
        "account_currency_decimal_places",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> AutocompleteAccount:
        """Create an instance of AutocompleteAccount from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> AutocompleteAccount:
        """Create an instance of AutocompleteAccount from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return AutocompleteAccount.parse_obj(obj)

        _obj = AutocompleteAccount.parse_obj(
            {
                "id": obj.get("id"),
                "name": obj.get("name"),
                "name_with_balance": obj.get("name_with_balance"),
                "active": obj.get("active"),
                "type": obj.get("type"),
                "currency_id": obj.get("currency_id"),
                "currency_name": obj.get("currency_name"),
                "currency_code": obj.get("currency_code"),
                "currency_symbol": obj.get("currency_symbol"),
                "currency_decimal_places": obj.get("currency_decimal_places"),
                "account_currency_id": obj.get("account_currency_id"),
                "account_currency_name": obj.get("account_currency_name"),
                "account_currency_code": obj.get("account_currency_code"),
                "account_currency_symbol": obj.get("account_currency_symbol"),
                "account_currency_decimal_places": obj.get(
                    "account_currency_decimal_places"
                ),
            }
        )
        return _obj
