# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr
from openapi_client.models.bill_repeat_frequency import BillRepeatFrequency


class BillUpdate(BaseModel):
    """
    BillUpdate
    """

    currency_id: Optional[StrictStr] = Field(
        default=None, description="Use either currency_id or currency_code"
    )
    currency_code: Optional[StrictStr] = Field(
        default=None, description="Use either currency_id or currency_code"
    )
    name: StrictStr = Field(...)
    amount_min: Optional[StrictStr] = None
    amount_max: Optional[StrictStr] = None
    var_date: Optional[datetime] = Field(default=None, alias="date")
    end_date: Optional[datetime] = Field(
        default=None,
        description="The date after which this bill is no longer valid or applicable",
    )
    extension_date: Optional[datetime] = Field(
        default=None,
        description="The date before which the bill must be renewed (or cancelled)",
    )
    repeat_freq: Optional[BillRepeatFrequency] = None
    skip: Optional[StrictInt] = Field(
        default=None,
        description="How often the bill must be skipped. 1 means a bi-monthly bill.",
    )
    active: Optional[StrictBool] = Field(
        default=None, description="If the bill is active."
    )
    notes: Optional[StrictStr] = None
    object_group_id: Optional[StrictStr] = Field(
        default=None,
        description="The group ID of the group this object is part of. NULL if no group.",
    )
    object_group_title: Optional[StrictStr] = Field(
        default=None, description="The name of the group. NULL if no group."
    )
    __properties = [
        "currency_id",
        "currency_code",
        "name",
        "amount_min",
        "amount_max",
        "date",
        "end_date",
        "extension_date",
        "repeat_freq",
        "skip",
        "active",
        "notes",
        "object_group_id",
        "object_group_title",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BillUpdate:
        """Create an instance of BillUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # set to None if notes (nullable) is None
        # and __fields_set__ contains the field
        if self.notes is None and "notes" in self.__fields_set__:
            _dict["notes"] = None

        # set to None if object_group_id (nullable) is None
        # and __fields_set__ contains the field
        if self.object_group_id is None and "object_group_id" in self.__fields_set__:
            _dict["object_group_id"] = None

        # set to None if object_group_title (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.object_group_title is None
            and "object_group_title" in self.__fields_set__
        ):
            _dict["object_group_title"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BillUpdate:
        """Create an instance of BillUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BillUpdate.parse_obj(obj)

        _obj = BillUpdate.parse_obj(
            {
                "currency_id": obj.get("currency_id"),
                "currency_code": obj.get("currency_code"),
                "name": obj.get("name"),
                "amount_min": obj.get("amount_min"),
                "amount_max": obj.get("amount_max"),
                "var_date": obj.get("date"),
                "end_date": obj.get("end_date"),
                "extension_date": obj.get("extension_date"),
                "repeat_freq": obj.get("repeat_freq"),
                "skip": obj.get("skip"),
                "active": obj.get("active"),
                "notes": obj.get("notes"),
                "object_group_id": obj.get("object_group_id"),
                "object_group_title": obj.get("object_group_title"),
            }
        )
        return _obj
