# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing import Optional, Set
from typing_extensions import Self


class BudgetLimitUpdate(BaseModel):
    """
    BudgetLimitUpdate
    """  # noqa: E501

    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    start: Optional[datetime] = Field(
        default=None, description="Start date of the budget limit."
    )
    end: Optional[datetime] = Field(
        default=None, description="End date of the budget limit."
    )
    budget_id: Optional[StrictStr] = Field(
        default=None, description="The budget ID of the associated budget."
    )
    object_has_currency_setting: Optional[StrictBool] = Field(
        default=None,
        description="Indicates whether the object has a currency setting. If false, the object uses the administration's primary currency.",
    )
    currency_id: Optional[StrictStr] = Field(
        default=None,
        description="The currency ID of the currency associated with this object.",
    )
    currency_name: Optional[StrictStr] = Field(
        default=None,
        description="The currency name of the currency associated with this object.",
    )
    currency_code: Optional[StrictStr] = Field(
        default=None,
        description="The currency code of the currency associated with this object.",
    )
    currency_symbol: Optional[StrictStr] = None
    currency_decimal_places: Optional[StrictInt] = None
    primary_currency_id: Optional[StrictStr] = Field(
        default=None,
        description="The currency ID of the administration's primary currency.",
    )
    primary_currency_name: Optional[StrictStr] = Field(
        default=None,
        description="The currency name of the administration's primary currency.",
    )
    primary_currency_code: Optional[StrictStr] = Field(
        default=None,
        description="The currency code of the administration's primary currency.",
    )
    primary_currency_symbol: Optional[StrictStr] = Field(
        default=None,
        description="The currency symbol of the administration's primary currency.",
    )
    primary_currency_decimal_places: Optional[StrictInt] = Field(
        default=None,
        description="The currency decimal places of the administration's primary currency.",
    )
    period: Optional[StrictStr] = Field(
        default=None,
        description="Period of the budget limit. Only used when auto-generated by auto-budget.",
    )
    amount: Optional[StrictStr] = None
    pc_amount: Optional[StrictStr] = Field(
        default=None,
        description="The amount of this budget limit in the user's primary currency, if the original amount is in a different currency.",
    )
    spent: Optional[StrictStr] = Field(
        default=None,
        description="Will be in the primary currency if this is turned on by the user.",
    )
    notes: Optional[StrictStr] = Field(
        default=None, description="Some notes for this specific budget limit."
    )
    fire_webhooks: Optional[StrictBool] = Field(
        default=True,
        description="Whether or not to fire the webhooks that are related to this event.",
    )
    __properties: ClassVar[List[str]] = [
        "created_at",
        "updated_at",
        "start",
        "end",
        "budget_id",
        "object_has_currency_setting",
        "currency_id",
        "currency_name",
        "currency_code",
        "currency_symbol",
        "currency_decimal_places",
        "primary_currency_id",
        "primary_currency_name",
        "primary_currency_code",
        "primary_currency_symbol",
        "primary_currency_decimal_places",
        "period",
        "amount",
        "pc_amount",
        "spent",
        "notes",
        "fire_webhooks",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BudgetLimitUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "created_at",
                "updated_at",
                "budget_id",
                "object_has_currency_setting",
                "currency_symbol",
                "currency_decimal_places",
                "primary_currency_id",
                "primary_currency_name",
                "primary_currency_code",
                "primary_currency_symbol",
                "primary_currency_decimal_places",
                "period",
                "pc_amount",
                "spent",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if period (nullable) is None
        # and model_fields_set contains the field
        if self.period is None and "period" in self.model_fields_set:
            _dict["period"] = None

        # set to None if pc_amount (nullable) is None
        # and model_fields_set contains the field
        if self.pc_amount is None and "pc_amount" in self.model_fields_set:
            _dict["pc_amount"] = None

        # set to None if spent (nullable) is None
        # and model_fields_set contains the field
        if self.spent is None and "spent" in self.model_fields_set:
            _dict["spent"] = None

        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict["notes"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BudgetLimitUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
                "start": obj.get("start"),
                "end": obj.get("end"),
                "budget_id": obj.get("budget_id"),
                "object_has_currency_setting": obj.get("object_has_currency_setting"),
                "currency_id": obj.get("currency_id"),
                "currency_name": obj.get("currency_name"),
                "currency_code": obj.get("currency_code"),
                "currency_symbol": obj.get("currency_symbol"),
                "currency_decimal_places": obj.get("currency_decimal_places"),
                "primary_currency_id": obj.get("primary_currency_id"),
                "primary_currency_name": obj.get("primary_currency_name"),
                "primary_currency_code": obj.get("primary_currency_code"),
                "primary_currency_symbol": obj.get("primary_currency_symbol"),
                "primary_currency_decimal_places": obj.get(
                    "primary_currency_decimal_places"
                ),
                "period": obj.get("period"),
                "amount": obj.get("amount"),
                "pc_amount": obj.get("pc_amount"),
                "spent": obj.get("spent"),
                "notes": obj.get("notes"),
                "fire_webhooks": (
                    obj.get("fire_webhooks")
                    if obj.get("fire_webhooks") is not None
                    else True
                ),
            }
        )
        return _obj
