# coding: utf-8

"""
    Firefly III API vv6.6.6

    This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2026-07-10 @ 08:26:33 (Europe/Amsterdam)</small> 

    The version of the OpenAPI document: vv6.6.6
    Contact: james@firefly-iii.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.array_entry_with_currency_and_sum import ArrayEntryWithCurrencyAndSum
from openapi_client.models.auto_budget_period import AutoBudgetPeriod
from openapi_client.models.auto_budget_type import AutoBudgetType
from typing import Optional, Set
from typing_extensions import Self
from pydantic_core import to_jsonable_python

class BudgetProperties(BaseModel):
    """
    BudgetProperties
    """ # noqa: E501
    created_at: Optional[datetime] = Field(default=None, json_schema_extra={"examples": ["2026-07-01T00:00:00Z"]})
    updated_at: Optional[datetime] = Field(default=None, json_schema_extra={"examples": ["2026-07-01T00:00:00Z"]})
    active: Optional[StrictBool] = Field(default=None, json_schema_extra={"examples": [False]})
    name: StrictStr = Field(json_schema_extra={"examples": ["Bills"]})
    order: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [5]})
    notes: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["Some notes"]})
    auto_budget_type: Optional[AutoBudgetType] = None
    auto_budget_period: Optional[AutoBudgetPeriod] = None
    object_group_id: Optional[StrictStr] = Field(default=None, description="The group ID of the group this object is part of. NULL if no group.", json_schema_extra={"examples": ["5"]})
    object_group_order: Optional[StrictInt] = Field(default=None, description="The order of the group. At least 1, for the highest sorting.", json_schema_extra={"examples": [5]})
    object_group_title: Optional[StrictStr] = Field(default=None, description="The name of the group. NULL if no group.", json_schema_extra={"examples": ["Example Group"]})
    object_has_currency_setting: Optional[StrictBool] = Field(default=None, description="Indicates whether the object has a currency setting. If false, the object uses the administration's primary currency.", json_schema_extra={"examples": [True]})
    currency_id: Optional[StrictStr] = Field(default=None, description="The currency ID of the currency associated with this object.", json_schema_extra={"examples": ["5"]})
    currency_name: Optional[StrictStr] = Field(default=None, description="The currency name of the currency associated with this object.", json_schema_extra={"examples": ["Euro"]})
    currency_code: Optional[StrictStr] = Field(default=None, description="The currency code of the currency associated with this object.", json_schema_extra={"examples": ["EUR"]})
    currency_symbol: Optional[StrictStr] = Field(default=None, json_schema_extra={"examples": ["$"]})
    currency_decimal_places: Optional[StrictInt] = Field(default=None, json_schema_extra={"examples": [2]})
    primary_currency_id: Optional[StrictStr] = Field(default=None, description="The currency ID of the administration's primary currency.", json_schema_extra={"examples": ["5"]})
    primary_currency_name: Optional[StrictStr] = Field(default=None, description="The currency name of the administration's primary currency.", json_schema_extra={"examples": ["Euro"]})
    primary_currency_code: Optional[StrictStr] = Field(default=None, description="The currency code of the administration's primary currency.", json_schema_extra={"examples": ["EUR"]})
    primary_currency_symbol: Optional[StrictStr] = Field(default=None, description="The currency symbol of the administration's primary currency.", json_schema_extra={"examples": ["$"]})
    primary_currency_decimal_places: Optional[StrictInt] = Field(default=None, description="The currency decimal places of the administration's primary currency.", json_schema_extra={"examples": [2]})
    auto_budget_amount: Optional[StrictStr] = Field(default=None, description="The amount for the auto-budget, if set.", json_schema_extra={"examples": ["-1012.12"]})
    pc_auto_budget_amount: Optional[StrictStr] = Field(default=None, description="The amount for the auto-budget, if set in the primary currency of the administration.", json_schema_extra={"examples": ["-1012.12"]})
    spent: Optional[List[ArrayEntryWithCurrencyAndSum]] = Field(default=None, description="Information on how much was spent in this budget. Is only filled in when the start and end date are submitted.")
    pc_spent: Optional[List[ArrayEntryWithCurrencyAndSum]] = Field(default=None, description="Information on how much was spent in this budget. Is only filled in when the start and end date are submitted. It is converted to the primary currency of the administration.")
    __properties: ClassVar[List[str]] = ["created_at", "updated_at", "active", "name", "order", "notes", "auto_budget_type", "auto_budget_period", "object_group_id", "object_group_order", "object_group_title", "object_has_currency_setting", "currency_id", "currency_name", "currency_code", "currency_symbol", "currency_decimal_places", "primary_currency_id", "primary_currency_name", "primary_currency_code", "primary_currency_symbol", "primary_currency_decimal_places", "auto_budget_amount", "pc_auto_budget_amount", "spent", "pc_spent"]

    model_config = ConfigDict(
        validate_by_name=True,
        validate_by_alias=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(to_jsonable_python(self.to_dict()))

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of BudgetProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set([
            "created_at",
            "updated_at",
            "order",
            "object_group_order",
            "object_has_currency_setting",
            "currency_symbol",
            "currency_decimal_places",
            "primary_currency_id",
            "primary_currency_name",
            "primary_currency_code",
            "primary_currency_symbol",
            "primary_currency_decimal_places",
            "spent",
            "pc_spent",
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in spent (list)
        _items = []
        if self.spent:
            for _item_spent in self.spent:
                _items.append(_item_spent.to_dict() if _item_spent is not None else None)
            _dict['spent'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in pc_spent (list)
        _items = []
        if self.pc_spent:
            for _item_pc_spent in self.pc_spent:
                _items.append(_item_pc_spent.to_dict() if _item_pc_spent is not None else None)
            _dict['pc_spent'] = _items
        # set to None if notes (nullable) is None
        # and model_fields_set contains the field
        if self.notes is None and "notes" in self.model_fields_set:
            _dict['notes'] = None

        # set to None if auto_budget_type (nullable) is None
        # and model_fields_set contains the field
        if self.auto_budget_type is None and "auto_budget_type" in self.model_fields_set:
            _dict['auto_budget_type'] = None

        # set to None if auto_budget_period (nullable) is None
        # and model_fields_set contains the field
        if self.auto_budget_period is None and "auto_budget_period" in self.model_fields_set:
            _dict['auto_budget_period'] = None

        # set to None if object_group_id (nullable) is None
        # and model_fields_set contains the field
        if self.object_group_id is None and "object_group_id" in self.model_fields_set:
            _dict['object_group_id'] = None

        # set to None if object_group_order (nullable) is None
        # and model_fields_set contains the field
        if self.object_group_order is None and "object_group_order" in self.model_fields_set:
            _dict['object_group_order'] = None

        # set to None if object_group_title (nullable) is None
        # and model_fields_set contains the field
        if self.object_group_title is None and "object_group_title" in self.model_fields_set:
            _dict['object_group_title'] = None

        # set to None if auto_budget_amount (nullable) is None
        # and model_fields_set contains the field
        if self.auto_budget_amount is None and "auto_budget_amount" in self.model_fields_set:
            _dict['auto_budget_amount'] = None

        # set to None if pc_auto_budget_amount (nullable) is None
        # and model_fields_set contains the field
        if self.pc_auto_budget_amount is None and "pc_auto_budget_amount" in self.model_fields_set:
            _dict['pc_auto_budget_amount'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of BudgetProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "created_at": obj.get("created_at"),
            "updated_at": obj.get("updated_at"),
            "active": obj.get("active"),
            "name": obj.get("name"),
            "order": obj.get("order"),
            "notes": obj.get("notes"),
            "auto_budget_type": obj.get("auto_budget_type"),
            "auto_budget_period": obj.get("auto_budget_period"),
            "object_group_id": obj.get("object_group_id"),
            "object_group_order": obj.get("object_group_order"),
            "object_group_title": obj.get("object_group_title"),
            "object_has_currency_setting": obj.get("object_has_currency_setting"),
            "currency_id": obj.get("currency_id"),
            "currency_name": obj.get("currency_name"),
            "currency_code": obj.get("currency_code"),
            "currency_symbol": obj.get("currency_symbol"),
            "currency_decimal_places": obj.get("currency_decimal_places"),
            "primary_currency_id": obj.get("primary_currency_id"),
            "primary_currency_name": obj.get("primary_currency_name"),
            "primary_currency_code": obj.get("primary_currency_code"),
            "primary_currency_symbol": obj.get("primary_currency_symbol"),
            "primary_currency_decimal_places": obj.get("primary_currency_decimal_places"),
            "auto_budget_amount": obj.get("auto_budget_amount"),
            "pc_auto_budget_amount": obj.get("pc_auto_budget_amount"),
            "spent": [ArrayEntryWithCurrencyAndSum.from_dict(_item) for _item in obj["spent"]] if obj.get("spent") is not None else None,
            "pc_spent": [ArrayEntryWithCurrencyAndSum.from_dict(_item) for _item in obj["pc_spent"]] if obj.get("pc_spent") is not None else None
        })
        return _obj


