# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr
from openapi_client.models.auto_budget_period import AutoBudgetPeriod
from openapi_client.models.auto_budget_type import AutoBudgetType


class BudgetUpdate(BaseModel):
    """
    BudgetUpdate
    """

    name: StrictStr = Field(...)
    active: Optional[StrictBool] = None
    order: Optional[StrictInt] = None
    notes: Optional[StrictStr] = None
    fire_webhooks: Optional[StrictBool] = Field(
        default=True,
        description="Whether or not to fire the webhooks that are related to this event.",
    )
    auto_budget_type: Optional[AutoBudgetType] = None
    auto_budget_currency_id: Optional[StrictStr] = Field(
        default=None,
        description="Use either currency_id or currency_code. Defaults to the user's financial administration's currency.",
    )
    auto_budget_currency_code: Optional[StrictStr] = Field(
        default=None,
        description="Use either currency_id or currency_code. Defaults to the user's financial administration's currency.",
    )
    auto_budget_amount: Optional[StrictStr] = None
    auto_budget_period: Optional[AutoBudgetPeriod] = None
    __properties = [
        "name",
        "active",
        "order",
        "notes",
        "fire_webhooks",
        "auto_budget_type",
        "auto_budget_currency_id",
        "auto_budget_currency_code",
        "auto_budget_amount",
        "auto_budget_period",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> BudgetUpdate:
        """Create an instance of BudgetUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # set to None if notes (nullable) is None
        # and __fields_set__ contains the field
        if self.notes is None and "notes" in self.__fields_set__:
            _dict["notes"] = None

        # set to None if auto_budget_type (nullable) is None
        # and __fields_set__ contains the field
        if self.auto_budget_type is None and "auto_budget_type" in self.__fields_set__:
            _dict["auto_budget_type"] = None

        # set to None if auto_budget_currency_id (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.auto_budget_currency_id is None
            and "auto_budget_currency_id" in self.__fields_set__
        ):
            _dict["auto_budget_currency_id"] = None

        # set to None if auto_budget_currency_code (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.auto_budget_currency_code is None
            and "auto_budget_currency_code" in self.__fields_set__
        ):
            _dict["auto_budget_currency_code"] = None

        # set to None if auto_budget_amount (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.auto_budget_amount is None
            and "auto_budget_amount" in self.__fields_set__
        ):
            _dict["auto_budget_amount"] = None

        # set to None if auto_budget_period (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.auto_budget_period is None
            and "auto_budget_period" in self.__fields_set__
        ):
            _dict["auto_budget_period"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> BudgetUpdate:
        """Create an instance of BudgetUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return BudgetUpdate.parse_obj(obj)

        _obj = BudgetUpdate.parse_obj(
            {
                "name": obj.get("name"),
                "active": obj.get("active"),
                "order": obj.get("order"),
                "notes": obj.get("notes"),
                "fire_webhooks": (
                    obj.get("fire_webhooks")
                    if obj.get("fire_webhooks") is not None
                    else True
                ),
                "auto_budget_type": obj.get("auto_budget_type"),
                "auto_budget_currency_id": obj.get("auto_budget_currency_id"),
                "auto_budget_currency_code": obj.get("auto_budget_currency_code"),
                "auto_budget_amount": obj.get("auto_budget_amount"),
                "auto_budget_period": obj.get("auto_budget_period"),
            }
        )
        return _obj
