# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.chart_data_point import ChartDataPoint
from openapi_client.models.chart_dataset_period_property import (
    ChartDatasetPeriodProperty,
)
from typing import Optional, Set
from typing_extensions import Self


class ChartDataSet(BaseModel):
    """
    ChartDataSet
    """  # noqa: E501

    label: Optional[StrictStr] = Field(
        default=None,
        description="This is the title of the current set. It can refer to an account, a budget or another object (by name).",
    )
    currency_id: Optional[StrictStr] = Field(
        default=None,
        description="The currency ID of the currency associated with this object.",
    )
    currency_name: Optional[StrictStr] = Field(
        default=None,
        description="The currency name of the currency associated with this object.",
    )
    currency_code: Optional[StrictStr] = Field(
        default=None,
        description="The currency code of the currency associated with this object.",
    )
    currency_symbol: Optional[StrictStr] = None
    currency_decimal_places: Optional[StrictInt] = None
    primary_currency_id: Optional[StrictStr] = Field(
        default=None,
        description="The currency ID of the administration's primary currency.",
    )
    primary_currency_name: Optional[StrictStr] = Field(
        default=None,
        description="The currency name of the administration's primary currency.",
    )
    primary_currency_code: Optional[StrictStr] = Field(
        default=None,
        description="The currency code of the administration's primary currency.",
    )
    primary_currency_symbol: Optional[StrictStr] = Field(
        default=None,
        description="The currency symbol of the administration's primary currency.",
    )
    primary_currency_decimal_places: Optional[StrictInt] = Field(
        default=None,
        description="The currency decimal places of the administration's primary currency.",
    )
    var_date: Optional[datetime] = Field(default=None, alias="date")
    start_date: Optional[datetime] = None
    end_date: Optional[datetime] = None
    type: Optional[StrictStr] = Field(
        default=None,
        description="Indicated the type of chart that is expected to be rendered. You can safely ignore this if you want.",
    )
    period: Optional[ChartDatasetPeriodProperty] = None
    y_axis_id: Optional[StrictInt] = Field(
        default=None,
        description="Used to indicate the Y axis for this data set. Is usually between 0 and 1 (left and right side of the chart).",
        alias="yAxisID",
    )
    entries: Optional[List[ChartDataPoint]] = Field(
        default=None,
        description="The actual entries for this data set. They 'key' value is the label for the data point. The value is the actual (numerical) value.",
    )
    pc_entries: Optional[List[ChartDataPoint]] = Field(
        default=None,
        description="The actual entries for this data set. They 'key' value is the label for the data point. The value is the actual (numerical) value.",
    )
    __properties: ClassVar[List[str]] = [
        "label",
        "currency_id",
        "currency_name",
        "currency_code",
        "currency_symbol",
        "currency_decimal_places",
        "primary_currency_id",
        "primary_currency_name",
        "primary_currency_code",
        "primary_currency_symbol",
        "primary_currency_decimal_places",
        "date",
        "start_date",
        "end_date",
        "type",
        "period",
        "yAxisID",
        "entries",
        "pc_entries",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ChartDataSet from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        * OpenAPI `readOnly` fields are excluded.
        """
        excluded_fields: Set[str] = set(
            [
                "currency_symbol",
                "currency_decimal_places",
                "primary_currency_id",
                "primary_currency_name",
                "primary_currency_code",
                "primary_currency_symbol",
                "primary_currency_decimal_places",
            ]
        )

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in entries (list)
        _items = []
        if self.entries:
            for _item_entries in self.entries:
                if _item_entries:
                    _items.append(_item_entries.to_dict())
            _dict["entries"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in pc_entries (list)
        _items = []
        if self.pc_entries:
            for _item_pc_entries in self.pc_entries:
                if _item_pc_entries:
                    _items.append(_item_pc_entries.to_dict())
            _dict["pc_entries"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ChartDataSet from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "label": obj.get("label"),
                "currency_id": obj.get("currency_id"),
                "currency_name": obj.get("currency_name"),
                "currency_code": obj.get("currency_code"),
                "currency_symbol": obj.get("currency_symbol"),
                "currency_decimal_places": obj.get("currency_decimal_places"),
                "primary_currency_id": obj.get("primary_currency_id"),
                "primary_currency_name": obj.get("primary_currency_name"),
                "primary_currency_code": obj.get("primary_currency_code"),
                "primary_currency_symbol": obj.get("primary_currency_symbol"),
                "primary_currency_decimal_places": obj.get(
                    "primary_currency_decimal_places"
                ),
                "date": obj.get("date"),
                "start_date": obj.get("start_date"),
                "end_date": obj.get("end_date"),
                "type": obj.get("type"),
                "period": obj.get("period"),
                "yAxisID": obj.get("yAxisID"),
                "entries": (
                    [ChartDataPoint.from_dict(_item) for _item in obj["entries"]]
                    if obj.get("entries") is not None
                    else None
                ),
                "pc_entries": (
                    [ChartDataPoint.from_dict(_item) for _item in obj["pc_entries"]]
                    if obj.get("pc_entries") is not None
                    else None
                ),
            }
        )
        return _obj
