# coding: utf-8

"""
    Firefly III API vv6.6.6

    This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2026-07-10 @ 08:26:33 (Europe/Amsterdam)</small> 

    The version of the OpenAPI document: vv6.6.6
    Contact: james@firefly-iii.org
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class ConfigValueUpdateFilter(str, Enum):
    """
    ConfigValueUpdateFilter
    """

    """
    allowed enum values
    """
    CONFIGURATION_DOT_IS_DEMO_SITE = 'configuration.is_demo_site'
    CONFIGURATION_DOT_PERMISSION_UPDATE_CHECK = 'configuration.permission_update_check'
    CONFIGURATION_DOT_LAST_UPDATE_CHECK = 'configuration.last_update_check'
    CONFIGURATION_DOT_SINGLE_USER_MODE = 'configuration.single_user_mode'
    CONFIGURATION_DOT_ENABLE_EXCHANGE_RATES = 'configuration.enable_exchange_rates'
    CONFIGURATION_DOT_USE_RUNNING_BALANCE = 'configuration.use_running_balance'
    CONFIGURATION_DOT_ENABLE_EXTERNAL_MAP = 'configuration.enable_external_map'
    CONFIGURATION_DOT_ENABLE_EXTERNAL_RATES = 'configuration.enable_external_rates'
    CONFIGURATION_DOT_ALLOW_WEBHOOKS = 'configuration.allow_webhooks'
    CONFIGURATION_DOT_VALID_URL_PROTOCOLS = 'configuration.valid_url_protocols'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of ConfigValueUpdateFilter from a JSON string"""
        return cls(json.loads(json_str))


