# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr


class CurrencyStore(BaseModel):
    """
    CurrencyStore
    """

    enabled: Optional[StrictBool] = Field(default=True, description="Defaults to true")
    primary: Optional[StrictBool] = Field(
        default=None,
        description="Make this currency the primary currency for the current administration. You can set this value to FALSE, in which case nothing will change to the primary currency. If you set it to TRUE, the current primary currency will no longer be the primary currency.",
    )
    code: StrictStr = Field(...)
    name: StrictStr = Field(...)
    symbol: StrictStr = Field(...)
    decimal_places: Optional[StrictInt] = Field(
        default=None, description="Supports 0-16 decimals."
    )
    __properties = ["enabled", "primary", "code", "name", "symbol", "decimal_places"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CurrencyStore:
        """Create an instance of CurrencyStore from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CurrencyStore:
        """Create an instance of CurrencyStore from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CurrencyStore.parse_obj(obj)

        _obj = CurrencyStore.parse_obj(
            {
                "enabled": (
                    obj.get("enabled") if obj.get("enabled") is not None else True
                ),
                "primary": obj.get("primary"),
                "code": obj.get("code"),
                "name": obj.get("name"),
                "symbol": obj.get("symbol"),
                "decimal_places": obj.get("decimal_places"),
            }
        )
        return _obj
