# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Dict
from pydantic import BaseModel, Field, StrictStr


class CurrencyExchangeRateStoreByDate(BaseModel):
    """
    CurrencyExchangeRateStoreByDate
    """

    var_from: StrictStr = Field(
        default=..., alias="from", description="The 'from'-currency"
    )
    rates: Dict[str, StrictStr] = Field(
        default=...,
        description="The actual entries for this data set. They 'key' value is 'to' currency. The value is the exchange rate.",
    )
    __properties = ["from", "rates"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CurrencyExchangeRateStoreByDate:
        """Create an instance of CurrencyExchangeRateStoreByDate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CurrencyExchangeRateStoreByDate:
        """Create an instance of CurrencyExchangeRateStoreByDate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CurrencyExchangeRateStoreByDate.parse_obj(obj)

        _obj = CurrencyExchangeRateStoreByDate.parse_obj(
            {"var_from": obj.get("from"), "rates": obj.get("rates")}
        )
        return _obj
