# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr


class CurrencyExchangeProperties(BaseModel):
    """
    CurrencyExchangeProperties
    """

    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    from_currency_id: Optional[StrictStr] = Field(
        default=None, description="Base currency ID for this exchange rate entry."
    )
    from_currency_name: Optional[StrictStr] = Field(
        default=None, description="Base currency name for this exchange rate entry."
    )
    from_currency_code: Optional[StrictStr] = Field(
        default=None, description="Base currency code for this exchange rate entry."
    )
    from_currency_symbol: Optional[StrictStr] = Field(
        default=None, description="Base currency symbol for this exchange rate entry."
    )
    from_currency_decimal_places: Optional[StrictInt] = Field(
        default=None,
        description="Base currency decimal places for this exchange rate entry.",
    )
    to_currency_id: Optional[StrictStr] = Field(
        default=None,
        description="Destination currency ID for this exchange rate entry.",
    )
    to_currency_name: Optional[StrictStr] = Field(
        default=None,
        description="Destination currency name for this exchange rate entry.",
    )
    to_currency_code: Optional[StrictStr] = Field(
        default=None,
        description="Destination currency code for this exchange rate entry.",
    )
    to_currency_symbol: Optional[StrictStr] = Field(
        default=None,
        description="Destination currency symbol for this exchange rate entry.",
    )
    to_currency_decimal_places: Optional[StrictInt] = Field(
        default=None,
        description="Destination currency decimal places for this exchange rate entry.",
    )
    rate: Optional[StrictStr] = Field(
        default=None,
        description="The actual exchange rate. How many 'to' currency will you get for 1 'from' currency?",
    )
    var_date: Optional[datetime] = Field(
        default=None, alias="date", description="Date and time of the exchange rate."
    )
    __properties = [
        "created_at",
        "updated_at",
        "from_currency_id",
        "from_currency_name",
        "from_currency_code",
        "from_currency_symbol",
        "from_currency_decimal_places",
        "to_currency_id",
        "to_currency_name",
        "to_currency_code",
        "to_currency_symbol",
        "to_currency_decimal_places",
        "rate",
        "date",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> CurrencyExchangeProperties:
        """Create an instance of CurrencyExchangeProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(
            by_alias=True,
            exclude={
                "created_at",
                "updated_at",
                "from_currency_id",
                "from_currency_name",
                "from_currency_code",
                "from_currency_symbol",
                "from_currency_decimal_places",
                "to_currency_id",
                "to_currency_name",
                "to_currency_code",
                "to_currency_symbol",
                "to_currency_decimal_places",
                "rate",
                "var_date",
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> CurrencyExchangeProperties:
        """Create an instance of CurrencyExchangeProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return CurrencyExchangeProperties.parse_obj(obj)

        _obj = CurrencyExchangeProperties.parse_obj(
            {
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
                "from_currency_id": obj.get("from_currency_id"),
                "from_currency_name": obj.get("from_currency_name"),
                "from_currency_code": obj.get("from_currency_code"),
                "from_currency_symbol": obj.get("from_currency_symbol"),
                "from_currency_decimal_places": obj.get("from_currency_decimal_places"),
                "to_currency_id": obj.get("to_currency_id"),
                "to_currency_name": obj.get("to_currency_name"),
                "to_currency_code": obj.get("to_currency_code"),
                "to_currency_symbol": obj.get("to_currency_symbol"),
                "to_currency_decimal_places": obj.get("to_currency_decimal_places"),
                "rate": obj.get("rate"),
                "var_date": obj.get("date"),
            }
        )
        return _obj
