# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr


class PiggyBankEventProperties(BaseModel):
    """
    PiggyBankEventProperties
    """

    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    amount: Optional[StrictStr] = None
    pc_amount: Optional[StrictStr] = None
    object_has_currency_setting: Optional[StrictBool] = Field(
        default=None,
        description="Indicates whether the object has a currency setting. If false, the object uses the administration's primary currency.",
    )
    currency_id: Optional[StrictStr] = Field(
        default=None,
        description="The currency ID of the currency associated with this object.",
    )
    currency_name: Optional[StrictStr] = Field(
        default=None,
        description="The currency name of the currency associated with this object.",
    )
    currency_code: Optional[StrictStr] = Field(
        default=None,
        description="The currency code of the currency associated with this object.",
    )
    currency_symbol: Optional[StrictStr] = None
    currency_decimal_places: Optional[StrictInt] = None
    primary_currency_id: Optional[StrictStr] = Field(
        default=None,
        description="The currency ID of the administration's primary currency.",
    )
    primary_currency_name: Optional[StrictStr] = Field(
        default=None,
        description="The currency name of the administration's primary currency.",
    )
    primary_currency_code: Optional[StrictStr] = Field(
        default=None,
        description="The currency code of the administration's primary currency.",
    )
    primary_currency_symbol: Optional[StrictStr] = Field(
        default=None,
        description="The currency symbol of the administration's primary currency.",
    )
    primary_currency_decimal_places: Optional[StrictInt] = Field(
        default=None,
        description="The currency decimal places of the administration's primary currency.",
    )
    transaction_journal_id: Optional[StrictStr] = Field(
        default=None, description="The journal associated with the event."
    )
    transaction_group_id: Optional[StrictStr] = Field(
        default=None, description="The transaction group associated with the event."
    )
    __properties = [
        "created_at",
        "updated_at",
        "amount",
        "pc_amount",
        "object_has_currency_setting",
        "currency_id",
        "currency_name",
        "currency_code",
        "currency_symbol",
        "currency_decimal_places",
        "primary_currency_id",
        "primary_currency_name",
        "primary_currency_code",
        "primary_currency_symbol",
        "primary_currency_decimal_places",
        "transaction_journal_id",
        "transaction_group_id",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PiggyBankEventProperties:
        """Create an instance of PiggyBankEventProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(
            by_alias=True,
            exclude={
                "object_has_currency_setting",
                "currency_symbol",
                "currency_decimal_places",
                "primary_currency_id",
                "primary_currency_name",
                "primary_currency_code",
                "primary_currency_symbol",
                "primary_currency_decimal_places",
            },
            exclude_none=True,
        )
        # set to None if transaction_journal_id (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.transaction_journal_id is None
            and "transaction_journal_id" in self.__fields_set__
        ):
            _dict["transaction_journal_id"] = None

        # set to None if transaction_group_id (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.transaction_group_id is None
            and "transaction_group_id" in self.__fields_set__
        ):
            _dict["transaction_group_id"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PiggyBankEventProperties:
        """Create an instance of PiggyBankEventProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PiggyBankEventProperties.parse_obj(obj)

        _obj = PiggyBankEventProperties.parse_obj(
            {
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
                "amount": obj.get("amount"),
                "pc_amount": obj.get("pc_amount"),
                "object_has_currency_setting": obj.get("object_has_currency_setting"),
                "currency_id": obj.get("currency_id"),
                "currency_name": obj.get("currency_name"),
                "currency_code": obj.get("currency_code"),
                "currency_symbol": obj.get("currency_symbol"),
                "currency_decimal_places": obj.get("currency_decimal_places"),
                "primary_currency_id": obj.get("primary_currency_id"),
                "primary_currency_name": obj.get("primary_currency_name"),
                "primary_currency_code": obj.get("primary_currency_code"),
                "primary_currency_symbol": obj.get("primary_currency_symbol"),
                "primary_currency_decimal_places": obj.get(
                    "primary_currency_decimal_places"
                ),
                "transaction_journal_id": obj.get("transaction_journal_id"),
                "transaction_group_id": obj.get("transaction_group_id"),
            }
        )
        return _obj
