# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr, conlist
from openapi_client.models.piggy_bank_account_read import PiggyBankAccountRead


class PiggyBankProperties(BaseModel):
    """
    PiggyBankProperties
    """

    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    name: StrictStr = Field(...)
    percentage: Optional[StrictInt] = Field(
        default=None,
        description="The percentage of the target amount that has been saved, if a target amount is set.",
    )
    start_date: Optional[datetime] = Field(
        default=None, description="The date you started with this piggy bank."
    )
    target_date: Optional[datetime] = Field(
        default=None, description="The date you intend to finish saving money."
    )
    order: Optional[StrictInt] = None
    active: Optional[StrictBool] = None
    notes: Optional[StrictStr] = None
    object_group_id: Optional[StrictStr] = Field(
        default=None,
        description="The group ID of the group this object is part of. NULL if no group.",
    )
    object_group_order: Optional[StrictInt] = Field(
        default=None,
        description="The order of the group. At least 1, for the highest sorting.",
    )
    object_group_title: Optional[StrictStr] = Field(
        default=None, description="The name of the group. NULL if no group."
    )
    accounts: Optional[conlist(PiggyBankAccountRead)] = None
    object_has_currency_setting: Optional[StrictBool] = Field(
        default=None,
        description="Indicates whether the object has a currency setting. If false, the object uses the administration's primary currency.",
    )
    currency_id: Optional[StrictStr] = Field(
        default=None,
        description="The currency ID of the currency associated with this object.",
    )
    currency_name: Optional[StrictStr] = Field(
        default=None,
        description="The currency name of the currency associated with this object.",
    )
    currency_code: Optional[StrictStr] = Field(
        default=None,
        description="The currency code of the currency associated with this object.",
    )
    currency_symbol: Optional[StrictStr] = None
    currency_decimal_places: Optional[StrictInt] = None
    primary_currency_id: Optional[StrictStr] = Field(
        default=None,
        description="The currency ID of the administration's primary currency.",
    )
    primary_currency_name: Optional[StrictStr] = Field(
        default=None,
        description="The currency name of the administration's primary currency.",
    )
    primary_currency_code: Optional[StrictStr] = Field(
        default=None,
        description="The currency code of the administration's primary currency.",
    )
    primary_currency_symbol: Optional[StrictStr] = Field(
        default=None,
        description="The currency symbol of the administration's primary currency.",
    )
    primary_currency_decimal_places: Optional[StrictInt] = Field(
        default=None,
        description="The currency decimal places of the administration's primary currency.",
    )
    target_amount: Optional[StrictStr] = Field(...)
    pc_target_amount: Optional[StrictStr] = Field(
        default=None,
        description="The target amount in the primary currency of the administration.",
    )
    current_amount: Optional[StrictStr] = None
    pc_current_amount: Optional[StrictStr] = Field(
        default=None,
        description="The current amount in the primary currency of the administration.",
    )
    left_to_save: Optional[StrictStr] = None
    pc_left_to_save: Optional[StrictStr] = None
    save_per_month: Optional[StrictStr] = None
    pc_save_per_month: Optional[StrictStr] = None
    __properties = [
        "created_at",
        "updated_at",
        "name",
        "percentage",
        "start_date",
        "target_date",
        "order",
        "active",
        "notes",
        "object_group_id",
        "object_group_order",
        "object_group_title",
        "accounts",
        "object_has_currency_setting",
        "currency_id",
        "currency_name",
        "currency_code",
        "currency_symbol",
        "currency_decimal_places",
        "primary_currency_id",
        "primary_currency_name",
        "primary_currency_code",
        "primary_currency_symbol",
        "primary_currency_decimal_places",
        "target_amount",
        "pc_target_amount",
        "current_amount",
        "pc_current_amount",
        "left_to_save",
        "pc_left_to_save",
        "save_per_month",
        "pc_save_per_month",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> PiggyBankProperties:
        """Create an instance of PiggyBankProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(
            by_alias=True,
            exclude={
                "created_at",
                "updated_at",
                "percentage",
                "active",
                "object_group_order",
                "object_has_currency_setting",
                "currency_symbol",
                "currency_decimal_places",
                "primary_currency_id",
                "primary_currency_name",
                "primary_currency_code",
                "primary_currency_symbol",
                "primary_currency_decimal_places",
                "save_per_month",
                "pc_save_per_month",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in accounts (list)
        _items = []
        if self.accounts:
            for _item in self.accounts:
                if _item:
                    _items.append(_item.to_dict())
            _dict["accounts"] = _items
        # set to None if percentage (nullable) is None
        # and __fields_set__ contains the field
        if self.percentage is None and "percentage" in self.__fields_set__:
            _dict["percentage"] = None

        # set to None if target_date (nullable) is None
        # and __fields_set__ contains the field
        if self.target_date is None and "target_date" in self.__fields_set__:
            _dict["target_date"] = None

        # set to None if notes (nullable) is None
        # and __fields_set__ contains the field
        if self.notes is None and "notes" in self.__fields_set__:
            _dict["notes"] = None

        # set to None if object_group_id (nullable) is None
        # and __fields_set__ contains the field
        if self.object_group_id is None and "object_group_id" in self.__fields_set__:
            _dict["object_group_id"] = None

        # set to None if object_group_order (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.object_group_order is None
            and "object_group_order" in self.__fields_set__
        ):
            _dict["object_group_order"] = None

        # set to None if object_group_title (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.object_group_title is None
            and "object_group_title" in self.__fields_set__
        ):
            _dict["object_group_title"] = None

        # set to None if target_amount (nullable) is None
        # and __fields_set__ contains the field
        if self.target_amount is None and "target_amount" in self.__fields_set__:
            _dict["target_amount"] = None

        # set to None if pc_target_amount (nullable) is None
        # and __fields_set__ contains the field
        if self.pc_target_amount is None and "pc_target_amount" in self.__fields_set__:
            _dict["pc_target_amount"] = None

        # set to None if left_to_save (nullable) is None
        # and __fields_set__ contains the field
        if self.left_to_save is None and "left_to_save" in self.__fields_set__:
            _dict["left_to_save"] = None

        # set to None if pc_left_to_save (nullable) is None
        # and __fields_set__ contains the field
        if self.pc_left_to_save is None and "pc_left_to_save" in self.__fields_set__:
            _dict["pc_left_to_save"] = None

        # set to None if save_per_month (nullable) is None
        # and __fields_set__ contains the field
        if self.save_per_month is None and "save_per_month" in self.__fields_set__:
            _dict["save_per_month"] = None

        # set to None if pc_save_per_month (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.pc_save_per_month is None
            and "pc_save_per_month" in self.__fields_set__
        ):
            _dict["pc_save_per_month"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> PiggyBankProperties:
        """Create an instance of PiggyBankProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return PiggyBankProperties.parse_obj(obj)

        _obj = PiggyBankProperties.parse_obj(
            {
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
                "name": obj.get("name"),
                "percentage": obj.get("percentage"),
                "start_date": obj.get("start_date"),
                "target_date": obj.get("target_date"),
                "order": obj.get("order"),
                "active": obj.get("active"),
                "notes": obj.get("notes"),
                "object_group_id": obj.get("object_group_id"),
                "object_group_order": obj.get("object_group_order"),
                "object_group_title": obj.get("object_group_title"),
                "accounts": (
                    [
                        PiggyBankAccountRead.from_dict(_item)
                        for _item in obj.get("accounts")
                    ]
                    if obj.get("accounts") is not None
                    else None
                ),
                "object_has_currency_setting": obj.get("object_has_currency_setting"),
                "currency_id": obj.get("currency_id"),
                "currency_name": obj.get("currency_name"),
                "currency_code": obj.get("currency_code"),
                "currency_symbol": obj.get("currency_symbol"),
                "currency_decimal_places": obj.get("currency_decimal_places"),
                "primary_currency_id": obj.get("primary_currency_id"),
                "primary_currency_name": obj.get("primary_currency_name"),
                "primary_currency_code": obj.get("primary_currency_code"),
                "primary_currency_symbol": obj.get("primary_currency_symbol"),
                "primary_currency_decimal_places": obj.get(
                    "primary_currency_decimal_places"
                ),
                "target_amount": obj.get("target_amount"),
                "pc_target_amount": obj.get("pc_target_amount"),
                "current_amount": obj.get("current_amount"),
                "pc_current_amount": obj.get("pc_current_amount"),
                "left_to_save": obj.get("left_to_save"),
                "pc_left_to_save": obj.get("pc_left_to_save"),
                "save_per_month": obj.get("save_per_month"),
                "pc_save_per_month": obj.get("pc_save_per_month"),
            }
        )
        return _obj
