# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictInt, StrictStr
from openapi_client.models.recurrence_repetition_type import RecurrenceRepetitionType


class RecurrenceRepetitionUpdate(BaseModel):
    """
    RecurrenceRepetitionUpdate
    """

    type: Optional[RecurrenceRepetitionType] = None
    moment: Optional[StrictStr] = Field(
        default=None,
        description="Information that defined the type of repetition. - For 'daily', this is empty. - For 'weekly', it is day of the week between 1 and 7 (Monday - Sunday). - For 'ndom', it is '1,2' or '4,5' or something else, where the first number is the week in the month, and the second number is the day in the week (between 1 and 7). '2,3' means: the 2nd Wednesday of the month - For 'monthly' it is the day of the month (1 - 31) - For yearly, it is a full date, ie '2025-12-01'. The year you use does not matter. ",
    )
    skip: Optional[StrictInt] = Field(
        default=None,
        description="How many occurrences to skip. 0 means skip nothing. 1 means every other.",
    )
    weekend: Optional[StrictInt] = Field(
        default=None,
        description="How to respond when the recurring transaction falls in the weekend. Possible values: 1. Do nothing, just create it 2. Create no transaction. 3. Skip to the previous Friday. 4. Skip to the next Monday. ",
    )
    __properties = ["type", "moment", "skip", "weekend"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RecurrenceRepetitionUpdate:
        """Create an instance of RecurrenceRepetitionUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RecurrenceRepetitionUpdate:
        """Create an instance of RecurrenceRepetitionUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RecurrenceRepetitionUpdate.parse_obj(obj)

        _obj = RecurrenceRepetitionUpdate.parse_obj(
            {
                "type": obj.get("type"),
                "moment": obj.get("moment"),
                "skip": obj.get("skip"),
                "weekend": obj.get("weekend"),
            }
        )
        return _obj
