# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr, conlist
from openapi_client.models.recurrence_repetition import RecurrenceRepetition
from openapi_client.models.recurrence_transaction import RecurrenceTransaction
from openapi_client.models.recurrence_transaction_type import RecurrenceTransactionType


class RecurrenceProperties(BaseModel):
    """
    RecurrenceProperties
    """

    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    type: Optional[RecurrenceTransactionType] = None
    title: Optional[StrictStr] = None
    description: Optional[StrictStr] = Field(
        default=None,
        description="Not to be confused with the description of the actual transaction(s) being created.",
    )
    first_date: Optional[date] = Field(
        default=None,
        description="First time the recurring transaction will fire. Must be after today.",
    )
    latest_date: Optional[date] = Field(
        default=None, description="Last time the recurring transaction has fired."
    )
    repeat_until: Optional[date] = Field(
        default=None,
        description="Date until the recurring transaction can fire. Use either this field or repetitions.",
    )
    apply_rules: Optional[StrictBool] = Field(
        default=None,
        description="Whether or not to fire the rules after the creation of a transaction.",
    )
    active: Optional[StrictBool] = Field(
        default=None, description="If the recurrence is even active."
    )
    nr_of_repetitions: Optional[StrictInt] = Field(
        default=None,
        description="Max number of created transactions. Use either this field or repeat_until.",
    )
    notes: Optional[StrictStr] = None
    repetitions: Optional[conlist(RecurrenceRepetition)] = None
    transactions: Optional[conlist(RecurrenceTransaction)] = None
    __properties = [
        "created_at",
        "updated_at",
        "type",
        "title",
        "description",
        "first_date",
        "latest_date",
        "repeat_until",
        "apply_rules",
        "active",
        "nr_of_repetitions",
        "notes",
        "repetitions",
        "transactions",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RecurrenceProperties:
        """Create an instance of RecurrenceProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(
            by_alias=True,
            exclude={
                "created_at",
                "updated_at",
                "latest_date",
            },
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in repetitions (list)
        _items = []
        if self.repetitions:
            for _item in self.repetitions:
                if _item:
                    _items.append(_item.to_dict())
            _dict["repetitions"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in transactions (list)
        _items = []
        if self.transactions:
            for _item in self.transactions:
                if _item:
                    _items.append(_item.to_dict())
            _dict["transactions"] = _items
        # set to None if latest_date (nullable) is None
        # and __fields_set__ contains the field
        if self.latest_date is None and "latest_date" in self.__fields_set__:
            _dict["latest_date"] = None

        # set to None if repeat_until (nullable) is None
        # and __fields_set__ contains the field
        if self.repeat_until is None and "repeat_until" in self.__fields_set__:
            _dict["repeat_until"] = None

        # set to None if nr_of_repetitions (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.nr_of_repetitions is None
            and "nr_of_repetitions" in self.__fields_set__
        ):
            _dict["nr_of_repetitions"] = None

        # set to None if notes (nullable) is None
        # and __fields_set__ contains the field
        if self.notes is None and "notes" in self.__fields_set__:
            _dict["notes"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RecurrenceProperties:
        """Create an instance of RecurrenceProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RecurrenceProperties.parse_obj(obj)

        _obj = RecurrenceProperties.parse_obj(
            {
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
                "type": obj.get("type"),
                "title": obj.get("title"),
                "description": obj.get("description"),
                "first_date": obj.get("first_date"),
                "latest_date": obj.get("latest_date"),
                "repeat_until": obj.get("repeat_until"),
                "apply_rules": obj.get("apply_rules"),
                "active": obj.get("active"),
                "nr_of_repetitions": obj.get("nr_of_repetitions"),
                "notes": obj.get("notes"),
                "repetitions": (
                    [
                        RecurrenceRepetition.from_dict(_item)
                        for _item in obj.get("repetitions")
                    ]
                    if obj.get("repetitions") is not None
                    else None
                ),
                "transactions": (
                    [
                        RecurrenceTransaction.from_dict(_item)
                        for _item in obj.get("transactions")
                    ]
                    if obj.get("transactions") is not None
                    else None
                ),
            }
        )
        return _obj
