# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List
from pydantic import BaseModel, Field, conlist
from openapi_client.models.meta import Meta
from openapi_client.models.page_link import PageLink
from openapi_client.models.recurrence_read import RecurrenceRead


class RecurrenceArray(BaseModel):
    """
    RecurrenceArray
    """

    data: conlist(RecurrenceRead) = Field(...)
    meta: Meta = Field(...)
    links: PageLink = Field(...)
    __properties = ["data", "meta", "links"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RecurrenceArray:
        """Create an instance of RecurrenceArray from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in data (list)
        _items = []
        if self.data:
            for _item in self.data:
                if _item:
                    _items.append(_item.to_dict())
            _dict["data"] = _items
        # override the default output from pydantic by calling `to_dict()` of meta
        if self.meta:
            _dict["meta"] = self.meta.to_dict()
        # override the default output from pydantic by calling `to_dict()` of links
        if self.links:
            _dict["links"] = self.links.to_dict()
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RecurrenceArray:
        """Create an instance of RecurrenceArray from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RecurrenceArray.parse_obj(obj)

        _obj = RecurrenceArray.parse_obj(
            {
                "data": (
                    [RecurrenceRead.from_dict(_item) for _item in obj.get("data")]
                    if obj.get("data") is not None
                    else None
                ),
                "meta": (
                    Meta.from_dict(obj.get("meta"))
                    if obj.get("meta") is not None
                    else None
                ),
                "links": (
                    PageLink.from_dict(obj.get("links"))
                    if obj.get("links") is not None
                    else None
                ),
            }
        )
        return _obj
