# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from openapi_client.models.rule_action_store import RuleActionStore
from openapi_client.models.rule_trigger_store import RuleTriggerStore
from openapi_client.models.rule_trigger_type import RuleTriggerType
from typing import Optional, Set
from typing_extensions import Self


class RuleStore(BaseModel):
    """
    RuleStore
    """  # noqa: E501

    title: StrictStr
    description: Optional[StrictStr] = None
    rule_group_id: StrictStr = Field(
        description="ID of the rule group under which the rule must be stored. Either this field or rule_group_title is mandatory."
    )
    rule_group_title: Optional[StrictStr] = Field(
        default=None,
        description="Title of the rule group under which the rule must be stored. Either this field or rule_group_id is mandatory.",
    )
    order: Optional[StrictInt] = None
    trigger: RuleTriggerType
    active: Optional[StrictBool] = Field(
        default=True,
        description="Whether or not the rule is even active. Default is true.",
    )
    strict: Optional[StrictBool] = Field(
        default=True,
        description="If the rule is set to be strict, ALL triggers must hit in order for the rule to fire. Otherwise, just one is enough. Default value is true.",
    )
    stop_processing: Optional[StrictBool] = Field(
        default=None,
        description="If this value is true and the rule is triggered, other rules  after this one in the group will be skipped. Default value is false.",
    )
    triggers: List[RuleTriggerStore]
    actions: List[RuleActionStore]
    __properties: ClassVar[List[str]] = [
        "title",
        "description",
        "rule_group_id",
        "rule_group_title",
        "order",
        "trigger",
        "active",
        "strict",
        "stop_processing",
        "triggers",
        "actions",
    ]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of RuleStore from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in triggers (list)
        _items = []
        if self.triggers:
            for _item_triggers in self.triggers:
                if _item_triggers:
                    _items.append(_item_triggers.to_dict())
            _dict["triggers"] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in actions (list)
        _items = []
        if self.actions:
            for _item_actions in self.actions:
                if _item_actions:
                    _items.append(_item_actions.to_dict())
            _dict["actions"] = _items
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of RuleStore from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate(
            {
                "title": obj.get("title"),
                "description": obj.get("description"),
                "rule_group_id": obj.get("rule_group_id"),
                "rule_group_title": obj.get("rule_group_title"),
                "order": obj.get("order"),
                "trigger": obj.get("trigger"),
                "active": obj.get("active") if obj.get("active") is not None else True,
                "strict": obj.get("strict") if obj.get("strict") is not None else True,
                "stop_processing": obj.get("stop_processing"),
                "triggers": (
                    [RuleTriggerStore.from_dict(_item) for _item in obj["triggers"]]
                    if obj.get("triggers") is not None
                    else None
                ),
                "actions": (
                    [RuleActionStore.from_dict(_item) for _item in obj["actions"]]
                    if obj.get("actions") is not None
                    else None
                ),
            }
        )
        return _obj
