# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr


class RuleGroupStore(BaseModel):
    """
    RuleGroupStore
    """

    title: StrictStr = Field(...)
    description: Optional[StrictStr] = None
    order: Optional[StrictInt] = None
    active: Optional[StrictBool] = None
    __properties = ["title", "description", "order", "active"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RuleGroupStore:
        """Create an instance of RuleGroupStore from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # set to None if description (nullable) is None
        # and __fields_set__ contains the field
        if self.description is None and "description" in self.__fields_set__:
            _dict["description"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RuleGroupStore:
        """Create an instance of RuleGroupStore from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RuleGroupStore.parse_obj(obj)

        _obj = RuleGroupStore.parse_obj(
            {
                "title": obj.get("title"),
                "description": obj.get("description"),
                "order": obj.get("order"),
                "active": obj.get("active"),
            }
        )
        return _obj
