# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictInt, StrictStr
from openapi_client.models.rule_action_keyword import RuleActionKeyword


class RuleAction(BaseModel):
    """
    RuleAction
    """

    id: Optional[StrictStr] = None
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    type: RuleActionKeyword = Field(...)
    value: Optional[StrictStr] = Field(
        default=...,
        description="The accompanying value the action will set, change or update. Can be empty, but for some types this value is mandatory.",
    )
    order: Optional[StrictInt] = Field(default=None, description="Order of the action")
    active: Optional[StrictBool] = Field(
        default=True, description="If the action is active. Defaults to true."
    )
    stop_processing: Optional[StrictBool] = Field(
        default=False,
        description="When true, other actions will not be fired after this action has fired. Defaults to false.",
    )
    __properties = [
        "id",
        "created_at",
        "updated_at",
        "type",
        "value",
        "order",
        "active",
        "stop_processing",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> RuleAction:
        """Create an instance of RuleAction from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(
            by_alias=True,
            exclude={
                "id",
                "created_at",
                "updated_at",
            },
            exclude_none=True,
        )
        # set to None if value (nullable) is None
        # and __fields_set__ contains the field
        if self.value is None and "value" in self.__fields_set__:
            _dict["value"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> RuleAction:
        """Create an instance of RuleAction from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return RuleAction.parse_obj(obj)

        _obj = RuleAction.parse_obj(
            {
                "id": obj.get("id"),
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
                "type": obj.get("type"),
                "value": obj.get("value"),
                "order": obj.get("order"),
                "active": obj.get("active") if obj.get("active") is not None else True,
                "stop_processing": (
                    obj.get("stop_processing")
                    if obj.get("stop_processing") is not None
                    else False
                ),
            }
        )
        return _obj
