# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg


class RuleTriggerKeyword(str, Enum):
    """
    The type of thing this trigger responds to. A limited set is possible
    """

    """
    allowed enum values
    """
    FROM_ACCOUNT_STARTS = "from_account_starts"
    FROM_ACCOUNT_ENDS = "from_account_ends"
    FROM_ACCOUNT_IS = "from_account_is"
    FROM_ACCOUNT_CONTAINS = "from_account_contains"
    TO_ACCOUNT_STARTS = "to_account_starts"
    TO_ACCOUNT_ENDS = "to_account_ends"
    TO_ACCOUNT_IS = "to_account_is"
    TO_ACCOUNT_CONTAINS = "to_account_contains"
    AMOUNT_LESS = "amount_less"
    AMOUNT_EXACTLY = "amount_exactly"
    AMOUNT_MORE = "amount_more"
    DESCRIPTION_STARTS = "description_starts"
    DESCRIPTION_ENDS = "description_ends"
    DESCRIPTION_CONTAINS = "description_contains"
    DESCRIPTION_IS = "description_is"
    TRANSACTION_TYPE = "transaction_type"
    CATEGORY_IS = "category_is"
    BUDGET_IS = "budget_is"
    TAG_IS = "tag_is"
    CURRENCY_IS = "currency_is"
    HAS_ATTACHMENTS = "has_attachments"
    HAS_NO_CATEGORY = "has_no_category"
    HAS_ANY_CATEGORY = "has_any_category"
    HAS_NO_BUDGET = "has_no_budget"
    HAS_ANY_BUDGET = "has_any_budget"
    HAS_NO_TAG = "has_no_tag"
    HAS_ANY_TAG = "has_any_tag"
    NOTES_CONTAINS = "notes_contains"
    NOTES_START = "notes_start"
    NOTES_END = "notes_end"
    NOTES_ARE = "notes_are"
    NO_NOTES = "no_notes"
    ANY_NOTES = "any_notes"
    SOURCE_ACCOUNT_IS = "source_account_is"
    DESTINATION_ACCOUNT_IS = "destination_account_is"
    SOURCE_ACCOUNT_STARTS = "source_account_starts"

    @classmethod
    def from_json(cls, json_str: str) -> RuleTriggerKeyword:
        """Create an instance of RuleTriggerKeyword from a JSON string"""
        return RuleTriggerKeyword(json.loads(json_str))
