# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg


class RuleTriggerType(str, Enum):
    """
    Which action is necessary for the rule to fire? Use either store-journal, update-journal or manual-activation.
    """

    """
    allowed enum values
    """
    STORE_MINUS_JOURNAL = "store-journal"
    UPDATE_MINUS_JOURNAL = "update-journal"
    MANUAL_MINUS_ACTIVATION = "manual-activation"

    @classmethod
    def from_json(cls, json_str: str) -> RuleTriggerType:
        """Create an instance of RuleTriggerType from a JSON string"""
        return RuleTriggerType(json.loads(json_str))
