# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import Optional
from pydantic import BaseModel, Field, StrictStr


class SystemInfoData(BaseModel):
    """
    SystemInfoData
    """

    version: Optional[StrictStr] = None
    api_version: Optional[StrictStr] = Field(
        default=None, description="Same value as the version field."
    )
    php_version: Optional[StrictStr] = None
    os: Optional[StrictStr] = None
    driver: Optional[StrictStr] = None
    __properties = ["version", "api_version", "php_version", "os", "driver"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> SystemInfoData:
        """Create an instance of SystemInfoData from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> SystemInfoData:
        """Create an instance of SystemInfoData from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return SystemInfoData.parse_obj(obj)

        _obj = SystemInfoData.parse_obj(
            {
                "version": obj.get("version"),
                "api_version": obj.get("api_version"),
                "php_version": obj.get("php_version"),
                "os": obj.get("os"),
                "driver": obj.get("driver"),
            }
        )
        return _obj
