# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import date, datetime
from typing import Optional, Union
from pydantic import BaseModel, Field, StrictFloat, StrictInt, StrictStr


class TagModel(BaseModel):
    """
    TagModel
    """

    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    tag: StrictStr = Field(default=..., description="The tag")
    var_date: Optional[date] = Field(
        default=None,
        alias="date",
        description="The date to which the tag is applicable.",
    )
    description: Optional[StrictStr] = None
    latitude: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Latitude of the tag's location, if applicable. Can be used to draw a map.",
    )
    longitude: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Latitude of the tag's location, if applicable. Can be used to draw a map.",
    )
    zoom_level: Optional[StrictInt] = Field(
        default=None,
        description="Zoom level for the map, if drawn. This to set the box right. Unfortunately this is a proprietary value because each map provider has different zoom levels.",
    )
    __properties = [
        "created_at",
        "updated_at",
        "tag",
        "date",
        "description",
        "latitude",
        "longitude",
        "zoom_level",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TagModel:
        """Create an instance of TagModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(
            by_alias=True,
            exclude={
                "created_at",
                "updated_at",
            },
            exclude_none=True,
        )
        # set to None if var_date (nullable) is None
        # and __fields_set__ contains the field
        if self.var_date is None and "var_date" in self.__fields_set__:
            _dict["date"] = None

        # set to None if description (nullable) is None
        # and __fields_set__ contains the field
        if self.description is None and "description" in self.__fields_set__:
            _dict["description"] = None

        # set to None if latitude (nullable) is None
        # and __fields_set__ contains the field
        if self.latitude is None and "latitude" in self.__fields_set__:
            _dict["latitude"] = None

        # set to None if longitude (nullable) is None
        # and __fields_set__ contains the field
        if self.longitude is None and "longitude" in self.__fields_set__:
            _dict["longitude"] = None

        # set to None if zoom_level (nullable) is None
        # and __fields_set__ contains the field
        if self.zoom_level is None and "zoom_level" in self.__fields_set__:
            _dict["zoom_level"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TagModel:
        """Create an instance of TagModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TagModel.parse_obj(obj)

        _obj = TagModel.parse_obj(
            {
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
                "tag": obj.get("tag"),
                "var_date": obj.get("date"),
                "description": obj.get("description"),
                "latitude": obj.get("latitude"),
                "longitude": obj.get("longitude"),
                "zoom_level": obj.get("zoom_level"),
            }
        )
        return _obj
