# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import List, Optional, Union
from pydantic import (
    BaseModel,
    Field,
    StrictBool,
    StrictFloat,
    StrictInt,
    StrictStr,
    conlist,
)
from openapi_client.models.account_type_property import AccountTypeProperty
from openapi_client.models.transaction_type_property import TransactionTypeProperty


class TransactionSplit(BaseModel):
    """
    TransactionSplit
    """

    user: Optional[StrictStr] = Field(default=None, description="User ID")
    transaction_journal_id: Optional[StrictStr] = Field(
        default=None,
        description="ID of the underlying transaction journal. Each transaction consists of a transaction group (see the top ID) and one or more journals making up the splits of the transaction. ",
    )
    type: TransactionTypeProperty = Field(...)
    var_date: datetime = Field(
        default=..., alias="date", description="Date of the transaction"
    )
    order: Optional[StrictInt] = Field(
        default=None, description="Order of this entry in the list of transactions."
    )
    object_has_currency_setting: Optional[StrictBool] = Field(
        default=None,
        description="Indicates whether the transaction has a currency setting. For transactions this is always true.",
    )
    currency_id: Optional[StrictStr] = Field(
        default=None, description="Currency ID for the currency of this transaction."
    )
    currency_code: Optional[StrictStr] = Field(
        default=None, description="Currency code for the currency of this transaction."
    )
    currency_symbol: Optional[StrictStr] = Field(
        default=None,
        description="Currency symbol for the currency of this transaction.",
    )
    currency_name: Optional[StrictStr] = Field(
        default=None, description="Currency name for the currency of this transaction."
    )
    currency_decimal_places: Optional[StrictInt] = Field(
        default=None, description="Number of decimals used in this currency."
    )
    foreign_currency_id: Optional[StrictStr] = Field(
        default=None,
        description="Currency ID of the foreign currency, if this transaction has a foreign amount.",
    )
    foreign_currency_code: Optional[StrictStr] = Field(
        default=None,
        description="Currency code of the foreign currency. Default is NULL.",
    )
    foreign_currency_symbol: Optional[StrictStr] = None
    foreign_currency_decimal_places: Optional[StrictInt] = Field(
        default=None, description="Number of decimals in the foreign currency."
    )
    primary_currency_id: Optional[StrictStr] = Field(
        default=None,
        description="Returns the primary currency ID of the administration. This currency is used as the currency for all `pc_*` amount and balance fields of this account.",
    )
    primary_currency_code: Optional[StrictStr] = Field(
        default=None,
        description="Returns the primary currency code of the administration. This currency is used as the currency for all `pc_*` amount and balance fields of this account.",
    )
    primary_currency_symbol: Optional[StrictStr] = Field(
        default=None, description="See the other `primary_*` fields."
    )
    primary_currency_decimal_places: Optional[StrictInt] = Field(
        default=None, description="See the other `primary_*` fields."
    )
    amount: StrictStr = Field(default=..., description="Amount of the transaction.")
    pc_amount: Optional[StrictStr] = Field(
        default=None,
        description="Amount of the transaction in the primary currency of this administration. The `primary_currency_*` fields reflect the currency used. This field is NULL if the user does have 'convert to primary' set to true in their settings.",
    )
    foreign_amount: Optional[StrictStr] = Field(
        default=None,
        description="The amount in the set foreign currency. May be NULL if the transaction does not have a foreign amount.",
    )
    pc_foreign_amount: Optional[StrictStr] = Field(
        default=None,
        description="Foreign amount of the transaction in the primary currency of this administration. The `primary_currency_*` fields reflect the currency used. This field is NULL if the user does have 'convert to primary' set to true in their settings.",
    )
    source_balance_after: Optional[StrictStr] = Field(
        default=None,
        description="The balance of the source account. This is the balance in the account's currency which may be different from this transaction, and is not provided in this model.",
    )
    pc_source_balance_after: Optional[StrictStr] = Field(
        default=None,
        description="The balance of the source account in the primary currency of this administration. The `primary_currency_*` fields reflect the currency used. This field is NULL if the user does have 'convert to primary' set to true in their settings.",
    )
    destination_balance_after: Optional[StrictStr] = Field(
        default=None,
        description="The balance of the destination account. This is the balance in the account's currency which may be different from this transaction, and is not provided in this model.",
    )
    pc_destination_balance_after: Optional[StrictStr] = Field(
        default=None,
        description="The balance of the destination account in the primary currency of this administration. The `primary_currency_*` fields reflect the currency used. This field is NULL if the user does have 'convert to primary' set to true in their settings.",
    )
    description: StrictStr = Field(
        default=..., description="Description of the transaction."
    )
    source_id: Optional[StrictStr] = Field(
        default=...,
        description="ID of the source account. For a withdrawal or a transfer, this must always be an asset account. For deposits, this must be a revenue account.",
    )
    source_name: Optional[StrictStr] = Field(
        default=None,
        description="Name of the source account. For a withdrawal or a transfer, this must always be an asset account. For deposits, this must be a revenue account. Can be used instead of the source_id. If the transaction is a deposit, the source_name can be filled in freely: the account will be created based on the name.",
    )
    source_iban: Optional[StrictStr] = None
    source_type: Optional[AccountTypeProperty] = None
    destination_id: Optional[StrictStr] = Field(
        default=...,
        description="ID of the destination account. For a deposit or a transfer, this must always be an asset account. For withdrawals this must be an expense account.",
    )
    destination_name: Optional[StrictStr] = Field(
        default=None,
        description="Name of the destination account. You can submit the name instead of the ID. For everything except transfers, the account will be auto-generated if unknown, so submitting a name is enough.",
    )
    destination_iban: Optional[StrictStr] = None
    destination_type: Optional[AccountTypeProperty] = None
    budget_id: Optional[StrictStr] = Field(
        default=None, description="The budget ID for this transaction."
    )
    budget_name: Optional[StrictStr] = Field(
        default=None, description="The name of the budget used."
    )
    category_id: Optional[StrictStr] = Field(
        default=None, description="The category ID for this transaction."
    )
    category_name: Optional[StrictStr] = Field(
        default=None,
        description="The name of the category to be used. If the category is unknown, it will be created. If the ID and the name point to different categories, the ID overrules the name.",
    )
    bill_id: Optional[StrictStr] = Field(
        default=None,
        description="The associated subscription ID for this transaction. `bill` refers to the OLD name for subscriptions and this field will be removed.",
    )
    bill_name: Optional[StrictStr] = Field(
        default=None,
        description="The associated subscription name for this transaction. `bill` refers to the OLD name for subscriptions and this field will be removed.",
    )
    subscription_id: Optional[StrictStr] = Field(
        default=None, description="The associated subscription ID for this transaction."
    )
    subscription_name: Optional[StrictStr] = Field(
        default=None,
        description="The associated subscription name for this transaction.",
    )
    reconciled: Optional[StrictBool] = Field(
        default=None,
        description="If the transaction has been reconciled already. When you set this, the amount can no longer be edited by the user.",
    )
    notes: Optional[StrictStr] = None
    tags: Optional[conlist(StrictStr)] = Field(
        default=None, description="Array of tags."
    )
    internal_reference: Optional[StrictStr] = Field(
        default=None, description="Reference to internal reference of other systems."
    )
    external_id: Optional[StrictStr] = Field(
        default=None, description="Reference to external ID in other systems."
    )
    external_url: Optional[StrictStr] = Field(
        default=None, description="External, custom URL for this transaction."
    )
    original_source: Optional[StrictStr] = Field(
        default=None,
        description="System generated identifier for original creator of transaction.",
    )
    recurrence_id: Optional[StrictStr] = Field(
        default=None, description="Reference to recurrence that made the transaction."
    )
    recurrence_total: Optional[StrictInt] = Field(
        default=None,
        description="Total number of transactions expected to be created by this recurrence repetition. Will be 0 if infinite.",
    )
    recurrence_count: Optional[StrictInt] = Field(
        default=None,
        description="The # of the current transaction created under this recurrence.",
    )
    import_hash_v2: Optional[StrictStr] = Field(
        default=None,
        description="Hash value of original import transaction (for duplicate detection).",
    )
    sepa_cc: Optional[StrictStr] = Field(default=None, description="SEPA Clearing Code")
    sepa_ct_op: Optional[StrictStr] = Field(
        default=None, description="SEPA Opposing Account Identifier"
    )
    sepa_ct_id: Optional[StrictStr] = Field(
        default=None, description="SEPA end-to-end Identifier"
    )
    sepa_db: Optional[StrictStr] = Field(
        default=None, description="SEPA mandate identifier"
    )
    sepa_country: Optional[StrictStr] = Field(default=None, description="SEPA Country")
    sepa_ep: Optional[StrictStr] = Field(
        default=None, description="SEPA External Purpose indicator"
    )
    sepa_ci: Optional[StrictStr] = Field(
        default=None, description="SEPA Creditor Identifier"
    )
    sepa_batch_id: Optional[StrictStr] = Field(
        default=None, description="SEPA Batch ID"
    )
    interest_date: Optional[datetime] = None
    book_date: Optional[datetime] = None
    process_date: Optional[datetime] = None
    due_date: Optional[datetime] = None
    payment_date: Optional[datetime] = None
    invoice_date: Optional[datetime] = None
    latitude: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Latitude of the transaction's location, if applicable. Can be used to draw a map.",
    )
    longitude: Optional[Union[StrictFloat, StrictInt]] = Field(
        default=None,
        description="Latitude of the transaction's location, if applicable. Can be used to draw a map.",
    )
    zoom_level: Optional[StrictInt] = Field(
        default=None,
        description="Zoom level for the map, if drawn. This to set the box right. Unfortunately this is a proprietary value because each map provider has different zoom levels.",
    )
    has_attachments: Optional[StrictBool] = Field(
        default=None, description="If the transaction has attachments."
    )
    __properties = [
        "user",
        "transaction_journal_id",
        "type",
        "date",
        "order",
        "object_has_currency_setting",
        "currency_id",
        "currency_code",
        "currency_symbol",
        "currency_name",
        "currency_decimal_places",
        "foreign_currency_id",
        "foreign_currency_code",
        "foreign_currency_symbol",
        "foreign_currency_decimal_places",
        "primary_currency_id",
        "primary_currency_code",
        "primary_currency_symbol",
        "primary_currency_decimal_places",
        "amount",
        "pc_amount",
        "foreign_amount",
        "pc_foreign_amount",
        "source_balance_after",
        "pc_source_balance_after",
        "destination_balance_after",
        "pc_destination_balance_after",
        "description",
        "source_id",
        "source_name",
        "source_iban",
        "source_type",
        "destination_id",
        "destination_name",
        "destination_iban",
        "destination_type",
        "budget_id",
        "budget_name",
        "category_id",
        "category_name",
        "bill_id",
        "bill_name",
        "subscription_id",
        "subscription_name",
        "reconciled",
        "notes",
        "tags",
        "internal_reference",
        "external_id",
        "external_url",
        "original_source",
        "recurrence_id",
        "recurrence_total",
        "recurrence_count",
        "import_hash_v2",
        "sepa_cc",
        "sepa_ct_op",
        "sepa_ct_id",
        "sepa_db",
        "sepa_country",
        "sepa_ep",
        "sepa_ci",
        "sepa_batch_id",
        "interest_date",
        "book_date",
        "process_date",
        "due_date",
        "payment_date",
        "invoice_date",
        "latitude",
        "longitude",
        "zoom_level",
        "has_attachments",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TransactionSplit:
        """Create an instance of TransactionSplit from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(
            by_alias=True,
            exclude={
                "user",
                "transaction_journal_id",
                "object_has_currency_setting",
                "currency_symbol",
                "foreign_currency_symbol",
                "foreign_currency_decimal_places",
                "primary_currency_id",
                "primary_currency_symbol",
                "primary_currency_decimal_places",
                "source_iban",
                "destination_iban",
                "budget_name",
                "original_source",
                "recurrence_id",
                "recurrence_total",
                "recurrence_count",
                "import_hash_v2",
            },
            exclude_none=True,
        )
        # set to None if order (nullable) is None
        # and __fields_set__ contains the field
        if self.order is None and "order" in self.__fields_set__:
            _dict["order"] = None

        # set to None if foreign_currency_id (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.foreign_currency_id is None
            and "foreign_currency_id" in self.__fields_set__
        ):
            _dict["foreign_currency_id"] = None

        # set to None if foreign_currency_code (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.foreign_currency_code is None
            and "foreign_currency_code" in self.__fields_set__
        ):
            _dict["foreign_currency_code"] = None

        # set to None if foreign_currency_symbol (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.foreign_currency_symbol is None
            and "foreign_currency_symbol" in self.__fields_set__
        ):
            _dict["foreign_currency_symbol"] = None

        # set to None if foreign_currency_decimal_places (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.foreign_currency_decimal_places is None
            and "foreign_currency_decimal_places" in self.__fields_set__
        ):
            _dict["foreign_currency_decimal_places"] = None

        # set to None if primary_currency_id (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.primary_currency_id is None
            and "primary_currency_id" in self.__fields_set__
        ):
            _dict["primary_currency_id"] = None

        # set to None if primary_currency_code (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.primary_currency_code is None
            and "primary_currency_code" in self.__fields_set__
        ):
            _dict["primary_currency_code"] = None

        # set to None if primary_currency_symbol (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.primary_currency_symbol is None
            and "primary_currency_symbol" in self.__fields_set__
        ):
            _dict["primary_currency_symbol"] = None

        # set to None if primary_currency_decimal_places (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.primary_currency_decimal_places is None
            and "primary_currency_decimal_places" in self.__fields_set__
        ):
            _dict["primary_currency_decimal_places"] = None

        # set to None if foreign_amount (nullable) is None
        # and __fields_set__ contains the field
        if self.foreign_amount is None and "foreign_amount" in self.__fields_set__:
            _dict["foreign_amount"] = None

        # set to None if source_balance_after (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.source_balance_after is None
            and "source_balance_after" in self.__fields_set__
        ):
            _dict["source_balance_after"] = None

        # set to None if pc_source_balance_after (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.pc_source_balance_after is None
            and "pc_source_balance_after" in self.__fields_set__
        ):
            _dict["pc_source_balance_after"] = None

        # set to None if destination_balance_after (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.destination_balance_after is None
            and "destination_balance_after" in self.__fields_set__
        ):
            _dict["destination_balance_after"] = None

        # set to None if pc_destination_balance_after (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.pc_destination_balance_after is None
            and "pc_destination_balance_after" in self.__fields_set__
        ):
            _dict["pc_destination_balance_after"] = None

        # set to None if source_id (nullable) is None
        # and __fields_set__ contains the field
        if self.source_id is None and "source_id" in self.__fields_set__:
            _dict["source_id"] = None

        # set to None if source_name (nullable) is None
        # and __fields_set__ contains the field
        if self.source_name is None and "source_name" in self.__fields_set__:
            _dict["source_name"] = None

        # set to None if source_iban (nullable) is None
        # and __fields_set__ contains the field
        if self.source_iban is None and "source_iban" in self.__fields_set__:
            _dict["source_iban"] = None

        # set to None if destination_id (nullable) is None
        # and __fields_set__ contains the field
        if self.destination_id is None and "destination_id" in self.__fields_set__:
            _dict["destination_id"] = None

        # set to None if destination_name (nullable) is None
        # and __fields_set__ contains the field
        if self.destination_name is None and "destination_name" in self.__fields_set__:
            _dict["destination_name"] = None

        # set to None if destination_iban (nullable) is None
        # and __fields_set__ contains the field
        if self.destination_iban is None and "destination_iban" in self.__fields_set__:
            _dict["destination_iban"] = None

        # set to None if budget_id (nullable) is None
        # and __fields_set__ contains the field
        if self.budget_id is None and "budget_id" in self.__fields_set__:
            _dict["budget_id"] = None

        # set to None if budget_name (nullable) is None
        # and __fields_set__ contains the field
        if self.budget_name is None and "budget_name" in self.__fields_set__:
            _dict["budget_name"] = None

        # set to None if category_id (nullable) is None
        # and __fields_set__ contains the field
        if self.category_id is None and "category_id" in self.__fields_set__:
            _dict["category_id"] = None

        # set to None if category_name (nullable) is None
        # and __fields_set__ contains the field
        if self.category_name is None and "category_name" in self.__fields_set__:
            _dict["category_name"] = None

        # set to None if bill_id (nullable) is None
        # and __fields_set__ contains the field
        if self.bill_id is None and "bill_id" in self.__fields_set__:
            _dict["bill_id"] = None

        # set to None if bill_name (nullable) is None
        # and __fields_set__ contains the field
        if self.bill_name is None and "bill_name" in self.__fields_set__:
            _dict["bill_name"] = None

        # set to None if subscription_id (nullable) is None
        # and __fields_set__ contains the field
        if self.subscription_id is None and "subscription_id" in self.__fields_set__:
            _dict["subscription_id"] = None

        # set to None if subscription_name (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.subscription_name is None
            and "subscription_name" in self.__fields_set__
        ):
            _dict["subscription_name"] = None

        # set to None if notes (nullable) is None
        # and __fields_set__ contains the field
        if self.notes is None and "notes" in self.__fields_set__:
            _dict["notes"] = None

        # set to None if tags (nullable) is None
        # and __fields_set__ contains the field
        if self.tags is None and "tags" in self.__fields_set__:
            _dict["tags"] = None

        # set to None if internal_reference (nullable) is None
        # and __fields_set__ contains the field
        if (
            self.internal_reference is None
            and "internal_reference" in self.__fields_set__
        ):
            _dict["internal_reference"] = None

        # set to None if external_id (nullable) is None
        # and __fields_set__ contains the field
        if self.external_id is None and "external_id" in self.__fields_set__:
            _dict["external_id"] = None

        # set to None if external_url (nullable) is None
        # and __fields_set__ contains the field
        if self.external_url is None and "external_url" in self.__fields_set__:
            _dict["external_url"] = None

        # set to None if original_source (nullable) is None
        # and __fields_set__ contains the field
        if self.original_source is None and "original_source" in self.__fields_set__:
            _dict["original_source"] = None

        # set to None if recurrence_id (nullable) is None
        # and __fields_set__ contains the field
        if self.recurrence_id is None and "recurrence_id" in self.__fields_set__:
            _dict["recurrence_id"] = None

        # set to None if recurrence_total (nullable) is None
        # and __fields_set__ contains the field
        if self.recurrence_total is None and "recurrence_total" in self.__fields_set__:
            _dict["recurrence_total"] = None

        # set to None if recurrence_count (nullable) is None
        # and __fields_set__ contains the field
        if self.recurrence_count is None and "recurrence_count" in self.__fields_set__:
            _dict["recurrence_count"] = None

        # set to None if import_hash_v2 (nullable) is None
        # and __fields_set__ contains the field
        if self.import_hash_v2 is None and "import_hash_v2" in self.__fields_set__:
            _dict["import_hash_v2"] = None

        # set to None if sepa_cc (nullable) is None
        # and __fields_set__ contains the field
        if self.sepa_cc is None and "sepa_cc" in self.__fields_set__:
            _dict["sepa_cc"] = None

        # set to None if sepa_ct_op (nullable) is None
        # and __fields_set__ contains the field
        if self.sepa_ct_op is None and "sepa_ct_op" in self.__fields_set__:
            _dict["sepa_ct_op"] = None

        # set to None if sepa_ct_id (nullable) is None
        # and __fields_set__ contains the field
        if self.sepa_ct_id is None and "sepa_ct_id" in self.__fields_set__:
            _dict["sepa_ct_id"] = None

        # set to None if sepa_db (nullable) is None
        # and __fields_set__ contains the field
        if self.sepa_db is None and "sepa_db" in self.__fields_set__:
            _dict["sepa_db"] = None

        # set to None if sepa_country (nullable) is None
        # and __fields_set__ contains the field
        if self.sepa_country is None and "sepa_country" in self.__fields_set__:
            _dict["sepa_country"] = None

        # set to None if sepa_ep (nullable) is None
        # and __fields_set__ contains the field
        if self.sepa_ep is None and "sepa_ep" in self.__fields_set__:
            _dict["sepa_ep"] = None

        # set to None if sepa_ci (nullable) is None
        # and __fields_set__ contains the field
        if self.sepa_ci is None and "sepa_ci" in self.__fields_set__:
            _dict["sepa_ci"] = None

        # set to None if sepa_batch_id (nullable) is None
        # and __fields_set__ contains the field
        if self.sepa_batch_id is None and "sepa_batch_id" in self.__fields_set__:
            _dict["sepa_batch_id"] = None

        # set to None if interest_date (nullable) is None
        # and __fields_set__ contains the field
        if self.interest_date is None and "interest_date" in self.__fields_set__:
            _dict["interest_date"] = None

        # set to None if book_date (nullable) is None
        # and __fields_set__ contains the field
        if self.book_date is None and "book_date" in self.__fields_set__:
            _dict["book_date"] = None

        # set to None if process_date (nullable) is None
        # and __fields_set__ contains the field
        if self.process_date is None and "process_date" in self.__fields_set__:
            _dict["process_date"] = None

        # set to None if due_date (nullable) is None
        # and __fields_set__ contains the field
        if self.due_date is None and "due_date" in self.__fields_set__:
            _dict["due_date"] = None

        # set to None if payment_date (nullable) is None
        # and __fields_set__ contains the field
        if self.payment_date is None and "payment_date" in self.__fields_set__:
            _dict["payment_date"] = None

        # set to None if invoice_date (nullable) is None
        # and __fields_set__ contains the field
        if self.invoice_date is None and "invoice_date" in self.__fields_set__:
            _dict["invoice_date"] = None

        # set to None if latitude (nullable) is None
        # and __fields_set__ contains the field
        if self.latitude is None and "latitude" in self.__fields_set__:
            _dict["latitude"] = None

        # set to None if longitude (nullable) is None
        # and __fields_set__ contains the field
        if self.longitude is None and "longitude" in self.__fields_set__:
            _dict["longitude"] = None

        # set to None if zoom_level (nullable) is None
        # and __fields_set__ contains the field
        if self.zoom_level is None and "zoom_level" in self.__fields_set__:
            _dict["zoom_level"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TransactionSplit:
        """Create an instance of TransactionSplit from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TransactionSplit.parse_obj(obj)

        _obj = TransactionSplit.parse_obj(
            {
                "user": obj.get("user"),
                "transaction_journal_id": obj.get("transaction_journal_id"),
                "type": obj.get("type"),
                "var_date": obj.get("date"),
                "order": obj.get("order"),
                "object_has_currency_setting": obj.get("object_has_currency_setting"),
                "currency_id": obj.get("currency_id"),
                "currency_code": obj.get("currency_code"),
                "currency_symbol": obj.get("currency_symbol"),
                "currency_name": obj.get("currency_name"),
                "currency_decimal_places": obj.get("currency_decimal_places"),
                "foreign_currency_id": obj.get("foreign_currency_id"),
                "foreign_currency_code": obj.get("foreign_currency_code"),
                "foreign_currency_symbol": obj.get("foreign_currency_symbol"),
                "foreign_currency_decimal_places": obj.get(
                    "foreign_currency_decimal_places"
                ),
                "primary_currency_id": obj.get("primary_currency_id"),
                "primary_currency_code": obj.get("primary_currency_code"),
                "primary_currency_symbol": obj.get("primary_currency_symbol"),
                "primary_currency_decimal_places": obj.get(
                    "primary_currency_decimal_places"
                ),
                "amount": obj.get("amount"),
                "pc_amount": obj.get("pc_amount"),
                "foreign_amount": obj.get("foreign_amount"),
                "pc_foreign_amount": obj.get("pc_foreign_amount"),
                "source_balance_after": obj.get("source_balance_after"),
                "pc_source_balance_after": obj.get("pc_source_balance_after"),
                "destination_balance_after": obj.get("destination_balance_after"),
                "pc_destination_balance_after": obj.get("pc_destination_balance_after"),
                "description": obj.get("description"),
                "source_id": obj.get("source_id"),
                "source_name": obj.get("source_name"),
                "source_iban": obj.get("source_iban"),
                "source_type": obj.get("source_type"),
                "destination_id": obj.get("destination_id"),
                "destination_name": obj.get("destination_name"),
                "destination_iban": obj.get("destination_iban"),
                "destination_type": obj.get("destination_type"),
                "budget_id": obj.get("budget_id"),
                "budget_name": obj.get("budget_name"),
                "category_id": obj.get("category_id"),
                "category_name": obj.get("category_name"),
                "bill_id": obj.get("bill_id"),
                "bill_name": obj.get("bill_name"),
                "subscription_id": obj.get("subscription_id"),
                "subscription_name": obj.get("subscription_name"),
                "reconciled": obj.get("reconciled"),
                "notes": obj.get("notes"),
                "tags": obj.get("tags"),
                "internal_reference": obj.get("internal_reference"),
                "external_id": obj.get("external_id"),
                "external_url": obj.get("external_url"),
                "original_source": obj.get("original_source"),
                "recurrence_id": obj.get("recurrence_id"),
                "recurrence_total": obj.get("recurrence_total"),
                "recurrence_count": obj.get("recurrence_count"),
                "import_hash_v2": obj.get("import_hash_v2"),
                "sepa_cc": obj.get("sepa_cc"),
                "sepa_ct_op": obj.get("sepa_ct_op"),
                "sepa_ct_id": obj.get("sepa_ct_id"),
                "sepa_db": obj.get("sepa_db"),
                "sepa_country": obj.get("sepa_country"),
                "sepa_ep": obj.get("sepa_ep"),
                "sepa_ci": obj.get("sepa_ci"),
                "sepa_batch_id": obj.get("sepa_batch_id"),
                "interest_date": obj.get("interest_date"),
                "book_date": obj.get("book_date"),
                "process_date": obj.get("process_date"),
                "due_date": obj.get("due_date"),
                "payment_date": obj.get("payment_date"),
                "invoice_date": obj.get("invoice_date"),
                "latitude": obj.get("latitude"),
                "longitude": obj.get("longitude"),
                "zoom_level": obj.get("zoom_level"),
                "has_attachments": obj.get("has_attachments"),
            }
        )
        return _obj
