# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, conlist
from openapi_client.models.transaction_split_update import TransactionSplitUpdate


class TransactionUpdate(BaseModel):
    """
    TransactionUpdate
    """

    apply_rules: Optional[StrictBool] = Field(
        default=None,
        description="Whether or not to apply rules when submitting transaction.",
    )
    fire_webhooks: Optional[StrictBool] = Field(
        default=True,
        description="Whether or not to fire the webhooks that are related to this event.",
    )
    group_title: Optional[StrictStr] = Field(
        default=None,
        description="Title of the transaction if it has been split in more than one piece. Empty otherwise.",
    )
    transactions: Optional[conlist(TransactionSplitUpdate)] = None
    __properties = ["apply_rules", "fire_webhooks", "group_title", "transactions"]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> TransactionUpdate:
        """Create an instance of TransactionUpdate from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        # override the default output from pydantic by calling `to_dict()` of each item in transactions (list)
        _items = []
        if self.transactions:
            for _item in self.transactions:
                if _item:
                    _items.append(_item.to_dict())
            _dict["transactions"] = _items
        # set to None if group_title (nullable) is None
        # and __fields_set__ contains the field
        if self.group_title is None and "group_title" in self.__fields_set__:
            _dict["group_title"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> TransactionUpdate:
        """Create an instance of TransactionUpdate from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return TransactionUpdate.parse_obj(obj)

        _obj = TransactionUpdate.parse_obj(
            {
                "apply_rules": obj.get("apply_rules"),
                "fire_webhooks": (
                    obj.get("fire_webhooks")
                    if obj.get("fire_webhooks") is not None
                    else True
                ),
                "group_title": obj.get("group_title"),
                "transactions": (
                    [
                        TransactionSplitUpdate.from_dict(_item)
                        for _item in obj.get("transactions")
                    ]
                    if obj.get("transactions") is not None
                    else None
                ),
            }
        )
        return _obj
