# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr
from openapi_client.models.user_blocked_code_property import UserBlockedCodeProperty
from openapi_client.models.user_role_property import UserRoleProperty


class User(BaseModel):
    """
    User
    """

    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    email: StrictStr = Field(default=..., description="The new users email address.")
    blocked: Optional[StrictBool] = Field(
        default=None, description="Boolean to indicate if the user is blocked."
    )
    blocked_code: Optional[UserBlockedCodeProperty] = None
    role: Optional[UserRoleProperty] = None
    __properties = [
        "created_at",
        "updated_at",
        "email",
        "blocked",
        "blocked_code",
        "role",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> User:
        """Create an instance of User from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(
            by_alias=True,
            exclude={
                "created_at",
                "updated_at",
            },
            exclude_none=True,
        )
        # set to None if blocked_code (nullable) is None
        # and __fields_set__ contains the field
        if self.blocked_code is None and "blocked_code" in self.__fields_set__:
            _dict["blocked_code"] = None

        # set to None if role (nullable) is None
        # and __fields_set__ contains the field
        if self.role is None and "role" in self.__fields_set__:
            _dict["role"] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> User:
        """Create an instance of User from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return User.parse_obj(obj)

        _obj = User.parse_obj(
            {
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
                "email": obj.get("email"),
                "blocked": obj.get("blocked"),
                "blocked_code": obj.get("blocked_code"),
                "role": obj.get("role"),
            }
        )
        return _obj
