# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


import json
import pprint
import re  # noqa: F401
from aenum import Enum, no_arg


class UserGroupReadRole(str, Enum):
    """
    The possible roles of the user in this user group are documented here: https://docs.firefly-iii.org/references/firefly-iii/api/
    """

    """
    allowed enum values
    """
    RO = "ro"
    MNG_TRX = "mng_trx"
    MNG_META = "mng_meta"
    READ_BUDGETS = "read_budgets"
    READ_PIGGIES = "read_piggies"
    READ_SUBSCRIPTIONS = "read_subscriptions"
    READ_RULES = "read_rules"
    READ_RECURRING = "read_recurring"
    READ_WEBHOOKS = "read_webhooks"
    READ_CURRENCIES = "read_currencies"
    MNG_BUDGETS = "mng_budgets"
    MNG_PIGGIES = "mng_piggies"
    MNG_SUBSCRIPTIONS = "mng_subscriptions"
    MNG_RULES = "mng_rules"
    MNG_RECURRING = "mng_recurring"
    MNG_WEBHOOKS = "mng_webhooks"
    MNG_CURRENCIES = "mng_currencies"
    VIEW_REPORTS = "view_reports"
    VIEW_MEMBERSHIPS = "view_memberships"
    FULL = "full"
    OWNER = "owner"

    @classmethod
    def from_json(cls, json_str: str) -> UserGroupReadRole:
        """Create an instance of UserGroupReadRole from a JSON string"""
        return UserGroupReadRole(json.loads(json_str))
