# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json


from typing import List, Optional
from pydantic import BaseModel, Field, StrictStr, conlist


class ValidationErrorResponseErrors(BaseModel):
    """
    ValidationErrorResponseErrors
    """

    email: Optional[conlist(StrictStr)] = None
    force: Optional[conlist(StrictStr)] = None
    blocked: Optional[conlist(StrictStr)] = None
    field: Optional[conlist(StrictStr)] = None
    role: Optional[conlist(StrictStr)] = None
    blocked_code: Optional[conlist(StrictStr)] = None
    name: Optional[conlist(StrictStr)] = None
    type: Optional[conlist(StrictStr)] = None
    iban: Optional[conlist(StrictStr)] = None
    start: Optional[conlist(StrictStr)] = None
    end: Optional[conlist(StrictStr)] = None
    var_date: Optional[conlist(StrictStr)] = Field(default=None, alias="date")
    __properties = [
        "email",
        "force",
        "blocked",
        "field",
        "role",
        "blocked_code",
        "name",
        "type",
        "iban",
        "start",
        "end",
        "date",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> ValidationErrorResponseErrors:
        """Create an instance of ValidationErrorResponseErrors from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(by_alias=True, exclude={}, exclude_none=True)
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> ValidationErrorResponseErrors:
        """Create an instance of ValidationErrorResponseErrors from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return ValidationErrorResponseErrors.parse_obj(obj)

        _obj = ValidationErrorResponseErrors.parse_obj(
            {
                "email": obj.get("email"),
                "force": obj.get("force"),
                "blocked": obj.get("blocked"),
                "field": obj.get("field"),
                "role": obj.get("role"),
                "blocked_code": obj.get("blocked_code"),
                "name": obj.get("name"),
                "type": obj.get("type"),
                "iban": obj.get("iban"),
                "start": obj.get("start"),
                "end": obj.get("end"),
                "var_date": obj.get("date"),
            }
        )
        return _obj
