# coding: utf-8

"""
Firefly III API v6.4.14

This is the documentation of the Firefly III API. Please report any bugs or issues. You may use the \"Authorize\" button to try the API below. <br><br> Please keep in mind that the demo site does **not** accept requests from `curl`, `colly`, `wget`, etc. You must use a browser or a tool like Insomnia to make your test requests. <br><br> To learn more about the idiosyncrasies of this API, please read about the API in the [Firefly III API documentation](https://docs.firefly-iii.org/references/firefly-iii/api/). <br><br> <small>This file was last generated on 2025-12-26 @ 15:17:41 (Europe/Amsterdam)</small>

The version of the OpenAPI document: v6.4.14
Contact: james@firefly-iii.org
Generated by OpenAPI Generator (https://openapi-generator.tech)

Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from datetime import datetime
from typing import List, Optional
from pydantic import BaseModel, Field, StrictBool, StrictStr, conlist
from openapi_client.models.webhook_delivery import WebhookDelivery
from openapi_client.models.webhook_response import WebhookResponse
from openapi_client.models.webhook_trigger import WebhookTrigger


class WebhookProperties(BaseModel):
    """
    WebhookProperties
    """

    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    active: Optional[StrictBool] = Field(
        default=None, description="Boolean to indicate if the webhook is active"
    )
    title: StrictStr = Field(
        default=..., description="A title for the webhook for easy recognition."
    )
    secret: Optional[StrictStr] = Field(
        default=None,
        description="A 24-character secret for the webhook. It's generated by Firefly III when saving a new webhook. If you submit a new secret through the PUT endpoint it will generate a new secret for the selected webhook, a new secret bearing no relation to whatever you just submitted.",
    )
    triggers: Optional[conlist(WebhookTrigger, max_items=3, min_items=1)] = None
    responses: Optional[conlist(WebhookResponse, max_items=1, min_items=1)] = None
    deliveries: Optional[conlist(WebhookDelivery, max_items=1, min_items=1)] = None
    url: StrictStr = Field(
        default=..., description="The URL of the webhook. Has to start with `https`."
    )
    __properties = [
        "created_at",
        "updated_at",
        "active",
        "title",
        "secret",
        "triggers",
        "responses",
        "deliveries",
        "url",
    ]

    class Config:
        """Pydantic configuration"""

        allow_population_by_field_name = True
        validate_assignment = True

    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.dict(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> WebhookProperties:
        """Create an instance of WebhookProperties from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self):
        """Returns the dictionary representation of the model using alias"""
        _dict = self.dict(
            by_alias=True,
            exclude={
                "created_at",
                "updated_at",
                "secret",
            },
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: dict) -> WebhookProperties:
        """Create an instance of WebhookProperties from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return WebhookProperties.parse_obj(obj)

        _obj = WebhookProperties.parse_obj(
            {
                "created_at": obj.get("created_at"),
                "updated_at": obj.get("updated_at"),
                "active": obj.get("active"),
                "title": obj.get("title"),
                "secret": obj.get("secret"),
                "triggers": obj.get("triggers"),
                "responses": obj.get("responses"),
                "deliveries": obj.get("deliveries"),
                "url": obj.get("url"),
            }
        )
        return _obj
